<template>
  <component
    :is="tag"
    class="ui-rating"
  >
    <!-- @slot Use this slot to replace legend template. -->
    <slot
      name="legend"
      v-bind="{
        legend
      }"
    >
      <legend
        v-if="legend"
        class="visual-hidden"
      >
        {{ legend }}
      </legend>
    </slot>
    <template
      v-for="index in maxScore"
      :key="index"
    >
      <!-- @slot Use this slot to replace option template. -->
      <slot
        name="option"
        v-bind="{
          index,
          rate,
          radioAttrs,
          ratingName,
          hoverHandler,
          finalScore,
          settings,
          translation: defaultProps.translation
        }"
      >
        <UiRadio
          v-model="rate"
          :value="`${index}`"
          :name="ratingName"
          class="ui-rating__option"
          @mouseover="hoverHandler($event, index)"
          @mouseleave="hoverHandler($event, index)"
        >
          <template #radio>
            <div
              class="ui-rating__radio"
              :class="{
                'ui-rating__radio--is-checked': index <= finalScore
              }"
            >
              <!-- fixme: performance -->
              <template v-if="index <= finalScore">
                <!-- @slot Use this slot to replace positive rating icon. -->
                <slot
                  name="icon-active"
                  v-bind="{
                    icon: settings.iconActive
                  }"
                >
                  <UiIcon
                    :icon="settings.iconActive"
                    class="ui-rating__icon"
                  />
                </slot>
              </template>
              <template v-else>
                <!-- @slot Use this slot to replace rating icon. -->
                <slot
                  name="icon"
                  v-bind="{
                    icon: settings.icon
                  }"
                >
                  <UiIcon
                    :icon="settings.icon"
                    class="ui-rating__icon"
                  />
                </slot>
              </template>
            </div>
          </template>
          <template #label>
            <span class="visual-hidden">{{ defaultProps.translation.stars(index) }}</span>
          </template>
        </UiRadio>
      </slot>
    </template>
  </component>
</template>

<script setup lang="ts">
import {
  computed,
  ref,
  useAttrs,
} from 'vue';
import type { PropType } from 'vue';
import { uid } from 'uid/single';
import UiRadio from '../../atoms/UiRadio/UiRadio.vue';
import UiIcon from '../../atoms/UiIcon/UiIcon.vue';
import type { PropsAttrs } from '../../../types/attrs';
import type { Icon } from '../../../types/icon';
import type { HTMLTag } from '../../../types/tag';

export type RatingValue = string | number;
export interface RatingSettings {
  icon: Icon;
  iconActive: Icon;
  [key: string]: unknown
}
export interface RatingTranslation {
  stars: (index: number) => string;
  [key: string]: unknown;
}
const props = defineProps({
  /**
   * Use this props to set current rate.
   */
  modelValue: {
    type: [String, Number] as PropType<RatingValue>,
    default: 0,
  },
  /**
   * Use this props to set max rate
   */
  max: {
    type: [String, Number] as PropType<RatingValue>,
    default: 1,
  },
  /**
   * Use this props to set rating name.
   * Default value is generated by uid i.e. `rating-<uid>`.
   */
  name: {
    type: String,
    default: '',
  },
  // TODO: remove in 0.6.0 / BEGIN
  /**
   * Use this props to pass attrs for UiRadio
   */
  radioAttrs: {
    type: Object as PropsAttrs,
    default: () => ({
    }),
  },
  // END
  /**
   * Use this props to setup item component.
   */
  settings: {
    type: Object as PropType<RatingSettings>,
    default: () => ({
      icon: 'star-outlined',
      iconActive: 'star-filled',
    }),
  },
  /**
   * Use this props to override labels inside component translation.
   */
  translation: {
    type: Object as PropType<RatingTranslation>,
    default: () => ({
      stars: (index: number) => (`${index} stars`),
    }),
  },
  /**
   * Use this props to set rating tag.
   */
  tag: {
    type: String as PropType<HTMLTag>,
    default: 'fieldset',
  },
  /**
   * Use this props to set legend.
   */
  legend: {
    type: String,
    default: '',
  },
});
const defaultProps = computed(() => ({
  translation: {
    stars: (index: number) => (`${index} stars`),
  },
}));
const emit = defineEmits<{(e:'update:modelValue', value: string): void}>();
const ratingName = computed(() => (
  props.name || `rating-${uid()}`
));
const rate = computed({
  get: (): string => (`${props.modelValue}`),
  set: (value: string): void => { emit('update:modelValue', value); },
});
const maxScore = computed(() => (typeof props.max === 'number' ? props.max : parseInt(props.max, 10)));
const hoverScore = ref(0);
function hoverHandler(event: Event, value: number) {
  const { type } = event;
  hoverScore.value = type === 'mouseover' ? value : 0;
}
const finalScore = computed(() => (
  hoverScore.value
    ? hoverScore.value
    : parseInt(rate.value, 10)));
// TODO: remove in 0.6.0 / BEGIN
const attrs = useAttrs();
if (Object.keys(props.radioAttrs).length > 0) {
  if (process.env.NODE_ENV === 'development') {
    console.warn('[@infermedica/component-library warn][UiPopover]: radioAttrs will be removed in 0.6.0.');
  }
}
// END
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-rating {
  $this: &;
  $element: rating;

  @at-root fieldset#{&} {
    border: none;
    padding: 0;
    margin: 0;
  }

  display: flex;
  align-items: center;
  justify-content: flex-start;

  &__option {
    --_rating-option-gap: #{functions.var($element + "-option", gap, var(--space-24))};

    position: relative;
    border: solid transparent;
    border-width: 0 var(--_rating-option-gap) 0 0;

    @include mixins.hover {
      #{$this}__icon {
        --icon-color: #{functions.var($element + "-hover-icon", color, var(--color-icon-secondary-hover))};
      }

      #{$this}__radio {
        &--is-checked {
          #{$this}__icon {
            --icon-color: #{functions.var($element + "-checked-hover-icon", color, var(--color-icon-primary-hover))};
          }
        }
      }
    }

    &:active {
      #{$this}__icon {
        --icon-color: #{functions.var($element + "-active-icon", color, var(--color-icon-secondary-active))};
      }

      #{$this}__radio {
        &--is-checked {
          #{$this}__icon {
            --icon-color: #{functions.var($element + "-checked-active-icon", color, var(--color-icon-primary-active))};
          }
        }
      }
    }

    [dir="rtl"] & {
      border-width: 0 0 0 var(--_rating-option-gap);
    }

    &:last-of-type {
      border-width: 0;

      [dir="rtl"] & {
        border-width: 0;
      }
    }
  }

  &__radio {
    display: flex;
    align-items: center;
    justify-content: center;

    &--is-checked {
      #{$this}__icon {
        --icon-color: #{functions.var($element + "-checked-icon", color, var(--color-icon-primary))};
      }
    }
  }

  &__icon {
    --icon-color: #{functions.var($element + "-icon", color, var(--color-icon-secondary))};
  }

  &--is-disabled {
    #{$this}__option {
      cursor: not-allowed;

      @include mixins.hover {
        #{$this}__icon {
          --icon-color: #{functions.var($element + "-hover-icon", color, var(--color-icon-disabled))};
        }

        #{$this}__radio {
          &--is-checked {
            #{$this}__icon {
              --icon-color: #{functions.var($element + "-checked-hover-icon", color, var(--color-icon-disabled))};
            }
          }
        }
      }

      &:active {
        #{$this}__icon {
          --icon-color: #{functions.var($element + "-icon", color, var(--color-icon-disabled))};
        }

        #{$this}__radio {
          &--is-checked {
            #{$this}__icon {
              --icon-color: #{functions.var($element + "-checked-active-icon", color, var(--color-icon-disabled))};
            }
          }
        }
      }
    }

    #{$this}__radio {
      &--is-checked {
        #{$this}__icon {
          --icon-color: #{functions.var($element + "-checked-icon", color, var(--color-icon-disabled))};
        }
      }
    }

    #{$this}__icon {
      --icon-color: #{functions.var($element + "-icon", color, var(--color-icon-disabled))};
    }
  }
}
</style>
