<!-- eslint-disable vuejs-accessibility/mouse-events-have-key-events -->
<template>
  <component
    :is="tag"
    :disabled="disabled"
    class="ui-rating"
  >
    <!-- @slot Use this slot to replace legend template. -->
    <slot
      name="legend"
      v-bind="{ legend }"
    >
      <legend
        v-if="legend"
        class="visual-hidden"
      >
        {{ legend }}
      </legend>
    </slot>
    <template
      v-for="(item, index) in itemsToRender"
      :key="index"
    >
      <!-- @slot Use this slot to replace option template. -->
      <slot
        name="option"
        v-bind="{
          index: item.index,
          rate,
          ratingName,
          hoverHandler,
          finalScore,
          settings,
          translation: defaultProps.translation
        }"
      >
        <UiRadio
          v-model="rate"
          v-bind="ratingItemAttrs(item)"
          :value="`${item.index}`"
          :input-attrs="{ name: ratingName }"
          class="ui-rating__option"
          @mouseover="hoverHandler($event, item.index)"
          @mouseleave="hoverHandler($event, item.index)"
        >
          <template
            #radio="{ radioElementAttrs }"
          >
            <div
              v-bind="radioElementAttrs"
              :class="[
                'ui-rating__radio',{ 'ui-rating__radio--is-checked': item.index <= finalScore }
              ]"
            >
              <!-- @slot Use this slot to replace rating icon. -->
              <slot
                name="icon"
                v-bind="{
                  index: item.index,
                  finalScore,
                  iconActiveAttrs: item.iconActiveAttrs,
                  iconDefaultAttrs: item.iconDefaultAttrs,
                }"
              >
                <template v-if="item.index <= finalScore">
                  <!-- @slot Use this slot to replace active rating icon. -->
                  <slot
                    name="icon-active"
                    v-bind="{ iconActiveAttrs: item.iconActiveAttrs }"
                  >
                    <UiIcon
                      v-bind="item.iconActiveAttrs"
                      class="ui-rating__icon"
                    />
                  </slot>
                </template>
                <template v-else>
                  <!-- @slot Use this slot to replace default rating icon. -->
                  <slot
                    name="icon-default"
                    v-bind="{ iconDefaultAttrs: item.iconDefaultAttrs }"
                  >
                    <UiIcon
                      v-bind="item.iconDefaultAttrs"
                      class="ui-rating__icon"
                    />
                  </slot>
                </template>
              </slot>
            </div>
          </template>
          <template
            #label="{ textLabelAttrs }"
          >
            <span
              v-bind="textLabelAttrs"
              class="visual-hidden"
            >{{ defaultProps.translation.stars(item.index) }}</span>
          </template>
        </UiRadio>
      </slot>
    </template>
  </component>
</template>

<script setup lang="ts">
import {
  computed,
  ref,
  type HTMLAttributes,
} from 'vue';
import { uid } from 'uid/single';
import UiRadio from '../../atoms/UiRadio/UiRadio.vue';
import type { RadioAttrsProps } from '../../atoms/UiRadio/UiRadio.vue';
import UiIcon from '../../atoms/UiIcon/UiIcon.vue';
import type { IconAttrsProps } from '../../atoms/UiIcon/UiIcon.vue';
import type {
  DefineAttrsProps,
  Icon,
  HTMLTag,
} from '../../../types';

export type RatingValue = string | number;
export interface RatingSettings {
  iconDefault?: Icon;
  iconActive?: Icon;
}
export interface RatingTranslation {
  stars?: (index: number) => string;
}
export interface RatingRenderItem extends RadioAttrsProps {
  index: number;
  iconActiveAttrs: IconAttrsProps;
  iconDefaultAttrs: IconAttrsProps;
}
export type RatingRadioAttrsProps = Partial<RatingRenderItem>
export interface RatingProps {
  /**
   * Use this props to set current rate.
   */
  modelValue?: RatingValue;
  /**
   * Use this props to set max rate
   */
  max?: RatingValue;
  /**
   * Use this props to set rating name.
   * Default value is generated by uid i.e. `rating-<uid>`.
   */
  name?: string;
  /**
   * Use this props to setup item component.
   */
  settings?: RatingSettings;
  /**
   * Use this props to override labels inside component translation.
   */
  translation?: RatingTranslation;
  /**
   * Use this props to set rating tag.
   */
  tag?: HTMLTag;
  /**
   * Use this props to disabled input.
   * Remember to use `ui-rating--is-disabled` class to style disabled rating.
   */
  disabled?: boolean;
  /**
   * Use this props to set legend.
   */
  legend?: string;
  /**
   * Use this props to pass attrs for option UiRadio.
   */
  radioOptionAttrs?: RatingRadioAttrsProps | RatingRadioAttrsProps[];
}
export type RatingAttrsProps<HTMLAttrs = HTMLAttributes> = DefineAttrsProps<RatingProps, HTMLAttrs>;
export interface RatingEmits{
  (e:'update:modelValue', value: string): void
}

const props = withDefaults(defineProps<RatingProps>(), {
  modelValue: 0,
  max: 1,
  name: '',
  settings: () => ({
    iconDefault: 'star-outlined',
    iconActive: 'star-filled',
  }),
  translation: () => ({ }),
  tag: 'fieldset',
  legend: '',
  radioOptionAttrs: () => ({}),
});
const defaultProps = computed(() => {
  const iconDefault: IconAttrsProps['icon'] = 'star-outlined';
  const iconActive: IconAttrsProps['icon'] = 'star-filled';
  return {
    translation: {
      stars: (index: number) => (`${index} stars`),
      ...props.translation,
    },
    settings: {
      iconDefault,
      iconActive,
    },
  };
});
const emit = defineEmits<RatingEmits>();
const ratingName = computed(() => (
  props.name || `rating-${uid()}`
));
const rate = computed({
  get: () => (`${props.modelValue}`),
  set: (value): void => {
    emit('update:modelValue', value);
  },
});
const maxScore = computed(() => (typeof props.max === 'number' ? props.max : parseInt(props.max, 10)));
const hoverScore = ref(0);
const hoverHandler = (event: Event, value: number) => {
  if (props.disabled) return;
  const { type } = event;
  hoverScore.value = type === 'mouseover' ? value : 0;
};
const finalScore = computed(() => (
  hoverScore.value
    ? hoverScore.value
    : parseInt(rate.value, 10)));
const itemsToRender = computed<RatingRenderItem[]>(() => (Array.from({ length: maxScore.value }, (_, index) => {
  const radioOptionAttrs = Array.isArray(props.radioOptionAttrs)
    ? props.radioOptionAttrs[index]
    : props.radioOptionAttrs;
  return {
    ...radioOptionAttrs,
    index: index + 1,
    iconActiveAttrs: {
      icon: defaultProps.value.settings.iconActive,
      ...radioOptionAttrs?.iconActiveAttrs,
    },
    iconDefaultAttrs: {
      icon: defaultProps.value.settings.iconDefault,
      ...radioOptionAttrs?.iconDefaultAttrs,
    },
    textLabelAttrs: {
      tag: 'div',
      ...radioOptionAttrs?.textLabelAttrs,
    },
  };
})));
const ratingItemAttrs = ({
  /* eslint-disable @typescript-eslint/no-unused-vars */
  iconActiveAttrs,
  iconDefaultAttrs,
  index,
  ...itemAttrs
  /* eslint-enable @typescript-eslint/no-unused-vars */
}: RatingRenderItem) => itemAttrs;
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-rating {
  $this: &;
  $element: rating;

  @at-root fieldset#{&} {
    padding: 0;
    border: none;
    margin: 0;
  }

  display: flex;
  align-items: center;
  justify-content: flex-start;

  &__option {
    --_rating-option-gap: #{functions.var($element + "-option", gap, var(--space-24))};

    @include mixins.use-logical($element + "-option", border-style, solid);
    @include mixins.use-logical($element + "-option", border-color, transparent);
    @include mixins.use-logical($element + "-option", border-width, 0 var(--_rating-option-gap) 0 0);

    position: relative;

    @include mixins.hover {
      #{$this}__icon {
        --icon-color: #{functions.var($element + "-hover-icon", color, var(--color-icon-secondary-hover))};
      }

      #{$this}__radio {
        &--is-checked {
          #{$this}__icon {
            --icon-color: #{functions.var($element + "-checked-hover-icon", color, var(--color-icon-primary-hover))};
          }
        }
      }
    }

    @include mixins.with-focus {
      &:focus-within {
        #{$this}__radio {
          box-shadow: var(--focus-outer);
        }
      }
    }

    &:active {
      #{$this}__icon {
        --icon-color: #{functions.var($element + "-active-icon", color, var(--color-icon-secondary-active))};
      }

      #{$this}__radio {
        &--is-checked {
          #{$this}__icon {
            --icon-color: #{functions.var($element + "-checked-active-icon", color, var(--color-icon-primary-active))};
          }
        }
      }
    }

    &:last-of-type {
      --#{$element}-option-border-inline-end-width: 0;
    }
  }

  &__radio {
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: var(--border-radius-button);

    &--is-checked {
      #{$this}__icon {
        --icon-color: #{functions.var($element + "-checked-icon", color, var(--color-icon-primary))};
      }
    }
  }

  &__icon {
    --icon-color: #{functions.var($element + "-icon", color, var(--color-icon-secondary))};
  }

  &--is-disabled {
    #{$this}__option {
      cursor: not-allowed;

      @include mixins.hover {
        #{$this}__icon {
          --icon-color: #{functions.var($element + "-hover-icon", color, var(--color-icon-disabled))};
        }

        #{$this}__radio {
          &--is-checked {
            #{$this}__icon {
              --icon-color: #{functions.var($element + "-checked-hover-icon", color, var(--color-icon-disabled))};
            }
          }
        }
      }

      &:active {
        #{$this}__icon {
          --icon-color: #{functions.var($element + "-icon", color, var(--color-icon-disabled))};
        }

        #{$this}__radio {
          &--is-checked {
            #{$this}__icon {
              --icon-color: #{functions.var($element + "-checked-active-icon", color, var(--color-icon-disabled))};
            }
          }
        }
      }
    }

    #{$this}__radio {
      &--is-checked {
        #{$this}__icon {
          --icon-color: #{functions.var($element + "-checked-icon", color, var(--color-icon-disabled))};
        }
      }
    }

    #{$this}__icon {
      --icon-color: #{functions.var($element + "-icon", color, var(--color-icon-disabled))};
    }
  }
}
</style>
