<template>
  <div class="ui-rating">
    <template
      v-for="index in maxScore"
      :key="index"
    >
      <!-- @slot Use this slot to replace option template. -->
      <slot
        name="option"
        v-bind="{index, rate, radioAttrs, ratingName, hoverHandler, finalScore, settings, translation}"
      >
        <UiRadio
          v-model="rate"
          v-bind="radioAttrs"
          :value="`${index}`"
          :name="ratingName"
          class="ui-rating__option"
          @mouseover="hoverHandler($event, index)"
          @mouseleave="hoverHandler($event, index)"
        >
          <template #radiobutton>
            <div class="ui-rating__radiobutton">
              <template v-if="index <= finalScore">
                <!-- @slot Use this slot to replace positive rating icon. -->
                <slot
                  name="icon-active"
                  v-bind="{icon: settings.iconActive}"
                >
                  <UiIcon
                    :icon="settings.iconActive"
                    class="ui-rating__icon ui-rating__icon--active"
                  />
                </slot>
              </template>
              <template v-else>
                <!-- @slot Use this slot to replace rating icon. -->
                <slot
                  name="icon"
                  v-bind="{icon: settings.icon}"
                >
                  <UiIcon
                    :icon="settings.icon"
                    class="ui-rating__icon"
                  />
                </slot>
              </template>
            </div>
          </template>
          <template #label>
            <span class="visual-hidden">{{ translation.stars(index) }}</span>
          </template>
        </UiRadio>
      </slot>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import type { PropType } from 'vue';
import { uid } from 'uid/single';
import UiRadio from '../../atoms/UiRadio/UiRadio.vue';
import UiIcon from '../../atoms/UiIcon/UiIcon.vue';
import type { PropsAttrs } from '../../../types/attrs';
import type { Icon } from '../../../types/icon';

export type RatingValue = string | number;
export interface RatingSettings {
  icon: Icon;
  iconActive: Icon;
  [key: string]: unknown
}
export interface RatingTranslation {
  stars: (index: number) => string;
  [key: string]: unknown;
}
const props = defineProps({
  /**
   * Use this props to set current rate.
   */
  modelValue: {
    type: [String, Number] as PropType<RatingValue>,
    default: 0,
  },
  /**
   * Use this props to set max rate
   */
  max: {
    type: [String, Number] as PropType<RatingValue>,
    default: 1,
  },
  /**
   * Use this props to set rating name.
   * Default value is generated by uid i.e. `rating-<uid>`.
   */
  name: {
    type: String,
    default: '',
  },
  /**
   * Use this props to pass attrs for UiRadio
   */
  radioAttrs: {
    type: Object as PropsAttrs,
    default: () => ({}),
  },
  /**
   * Use this props to setup item component.
   */
  settings: {
    type: Object as PropType<RatingSettings>,
    default: () => ({
      icon: 'star-outlined',
      iconActive: 'star-filled',
    }),
  },
  /**
   * Use this props to override labels inside component translation.
   */
  translation: {
    type: Object as PropType<RatingTranslation>,
    default: () => ({
      stars: (index: number) => (`${index} stars`),
    }),
  },
});
const emit = defineEmits<{(e:'update:modelValue', value: string): void}>();
const ratingName = computed(() => (
  props.name || `rating-${uid()}`
));
const rate = computed({
  get: (): string => (`${props.modelValue}`),
  set: (value: string): void => { emit('update:modelValue', value); },
});
const maxScore = computed(() => (typeof props.max === 'number' ? props.max : parseInt(props.max, 10)));
const hoverScore = ref(0);
function hoverHandler(event: Event, value: number) {
  const { type } = event;
  hoverScore.value = type === 'mouseover' ? value : 0;
}
const finalScore = computed(() => (
  hoverScore.value
    ? hoverScore.value
    : parseInt(rate.value, 10)));
</script>

<style lang="scss">
@import "../../../styles/mixins/mixins";

.ui-rating {
  $this: &;

  --radio-size: var(--rating-icon-size, 1.5rem);
  --radio-background: transparent;

  display: inline-flex;

  &__option {
    @include no-highlight;

    padding: var(--rating-option, 0 var(--space-24) 0 0);

    [dir="rtl"] & {
      padding: var(--rating-option, 0 0 0 var(--space-24));
    }

    &:last-of-type {
      [dir] & {
        padding: var(--rating-option, 0);
      }
    }
  }

  &__radiobutton {
    display: flex;
    border-radius: var(--border-radius-button);
    pointer-events: none;
  }

  input {
    @include focus {
      & + #{$this}__radiobutton {
        box-shadow: var(--focus-outer);
      }
    }
  }

  &__icon {
    --icon-size: var(--rating-icon-size, 1.5rem);
    --icon-color: var(--rating-icon-icon-color, var(--color-icon-secondary));

    &:active {
      --icon-color: var(--rating-icon-active-icon-color, var(--color-icon-secondary-active));
    }

    &--active {
      --icon-color: var(--rating-icon-positive-icon-color, var(--color-icon-primary));

      &:active {
        --icon-color: var(--rating-icon-positive-active-icon-color, var(--color-icon-primary-active));
      }
    }

    @media (hover: hover) {
      &:hover {
        --icon-color: var(--rating-icon-hover-icon-color, var(--color-icon-secondary-hover));
      }

      &--active:hover {
        --icon-color: var(--rating-icon-positive-hover-icon-color, var(--color-icon-primary-hover));
      }
    }
  }

  &--is-disabled {
    #{$this}__icon {
      --rating-icon-icon-color: var(--rating-icon-disabled-icon-color, var(--color-icon-disabled));
      --rating-icon-hover-icon-color: var(--rating-icon-disabled-hover-icon-color, var(--color-icon-disabled));
      --rating-icon-active-icon-color: var(--rating-icon-disabled-active-icon-color, var(--color-icon-disabled));
      --rating-icon-positive-icon-color: var(--rating-icon-disabled-positive-icon-color, var(--color-icon-disabled));
      --rating-icon-positive-hover-icon-color:
        var(
          --rating-icon-disabled-positive-hover-icon-color,
          var(--color-icon-disabled)
        );
      --rating-icon-positive-active-icon-color:
        var(
          --rating-icon-disabled-positive-active-icon-color,
          var(--color-icon-disabled)
        );
    }
  }
}
</style>
