<template>
  <div class="ui-phone-number">
    <!-- @slot Use this slot to replace phone number prefix template.-->
    <slot
      name="prefix"
      v-bind="modelValue"
    >
      <UiPhoneNumberPrefix
        v-model="modelValue.prefix"
        :language="language"
        :country-codes="countryCodes"
      />
    </slot>
    <!-- @slot Use this slot to replace phone number input template.-->
    <slot
      name="input"
      v-bind="{
        inputId,
        modelValue,
        placeholder,
        hasError,
      }"
    >
      <UiPhoneNumberInput
        :id="inputId"
        v-model="modelValue.phoneNumber"
        :placeholder="placeholder"
        :has-error="hasError"
      />
    </slot>
  </div>
</template>

<script setup lang="ts">
import {
  computed,
  useAttrs,
} from 'vue';
import { uid } from 'uid/single';
import type { Alpha2Code } from 'i18n-iso-countries';
import UiPhoneNumberPrefix from './_internal/UiPhoneNumberPrefix/UiPhoneNumberPrefix.vue';
import UiPhoneNumberInput from './_internal/UiPhoneNumberInput/UiPhoneNumberInput.vue';
import type { DefineAttrsProps } from '../../../types';
import type { PhoneCodeType } from './helpers';

export interface PhoneNumberProps {
  /**
   * Use this props to set input id and label for
   * Default value is generated by uid i.e. `input-<uid>`.
   */
  id?: string,
  /**
   * Use this props to set default prefix phone code and phone number.
   */
  modelValue?: {
    prefix?: PhoneCodeType,
    phoneNumber?: string,
  },
  /**
   * Use this props to set input placeholder.
   */
  placeholder?: string,
  /**
   * Use this props to set phone number prefix default language.
   */
  language?: string,
  /**
   * Use this props to set countries available on dropdown.
   */
  countryCodes?: Alpha2Code[],
}
export type PhoneNumberAttrsProps = DefineAttrsProps<PhoneNumberProps>;

const emit = defineEmits([ 'update:modelValue' ]);
const props = withDefaults(defineProps<PhoneNumberProps>(), {
  id: '',
  modelValue: () => ({
    prefix: {
      code: '+1',
      countryCode: 'US',
    },
    phoneNumber: '',
  }),
  placeholder: 'Enter phone number',
  language: 'en',
  countryCodes: () => ([]),
});
const inputId = computed(() => (
  props.id || `phone-number-${uid()}`
));
const modelValue = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value),
});
const attrs:PhoneNumberAttrsProps = useAttrs();
const hasError = computed(() => (('class' in attrs)
  ? attrs.class.includes('ui-phone-number--has-error')
  : false));
</script>

<style lang="scss">
@use "../../../styles/functions";

.ui-phone-number {
  display: flex;
  flex-direction: column;
  gap: var(--space-8);
}
</style>
