<template>
  <div class="ui-phone-number">
    <!-- @slot Use this slot to replace phone number prefix template.-->
    <slot
      name="prefix"
      v-bind="{
        modelValue,
        languageData,
      }"
    >
      <UiPhoneNumberPrefix
        v-model="modelValue.prefix"
        :language-data="languageData"
        :country-codes="countryCodes"
      />
    </slot>
    <!-- @slot Use this slot to replace phone number input template.-->
    <slot
      name="input"
      v-bind="{
        inputId,
        modelValue,
        placeholder,
        hasError,
      }"
    >
      <UiPhoneNumberInput
        :id="inputId"
        v-model="modelValue.phoneNumber"
        :placeholder="placeholder"
        :has-error="hasError"
      />
    </slot>
  </div>
</template>

<script setup lang="ts">
import {
  computed,
  useAttrs,
} from 'vue';
import { uid } from 'uid/single';
import { DefineAttrsProps } from '@/types';
import UiPhoneNumberPrefix from './_internal/UiPhoneNumberPrefix/UiPhoneNumberPrefix.vue';
import UiPhoneNumberInput from './_internal/UiPhoneNumberInput/UiPhoneNumberInput.vue';
import type {
  PhoneCodeType,
  SupportedCountryCodeType,
} from './helpers';

export type CountryCodes = (PhoneCodeType & Record<string, unknown>)[];

export interface UiPhoneNumberProps {
  /**
   * Use this props to set input id and label for
   * Default value is generated by uid i.e. `input-<uid>`.
   */
   id?: string,
   /**
   * Use this props to set default prefix phone code and phone number.
   */
   modelValue?: {
    prefix?: PhoneCodeType,
    phoneNumber?: string,
   },
  /**
   * Use this props to set input placeholder.
   */
  placeholder?: string,
   /**
   * Use this props to set phone number prefix default language.
   */
   languageData?: {
    country: SupportedCountryCodeType,
    language: string,
   },
  /**
   * Use this props to set country code items.
   */
  countryCodes?: CountryCodes,
}
export type PhoneNumberAttrsProps = DefineAttrsProps<UiPhoneNumberProps>;

const emit = defineEmits([ 'update:modelValue' ]);
const props = withDefaults(defineProps<UiPhoneNumberProps>(), {
  id: '',
  modelValue: () => ({
    prefix: {
      code: '+1',
      countryCode: 'US',
      country: 'United States of America',
    },
    phoneNumber: '',
  }),
  placeholder: 'Enter phone number',
  languageData: () => ({
    country: 'us',
    language: 'en',
  }),
  countryCodes: () => ([]),
});
const inputId = computed(() => (
  props.id || `phone-number-${uid()}`
));
const modelValue = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value),
});
const attrs:PhoneNumberAttrsProps = useAttrs();
const hasError = computed(() => ((!attrs.class)
  ? false
  : attrs.class.includes('ui-phone-number--has-error')));
</script>

<style lang="scss">
@use "../../../styles/functions";

.ui-phone-number {
  display: flex;
  flex-direction: column;
  gap: var(--space-8);
}
</style>
