<template>
  <UiButton
    :id="tileId"
    :class="[
      'ui-button--outlined ui-tile',{ 'ui-tile--is-checked': isChecked }
    ]"
    role="radio"
    :aria-checked="`${isChecked}`"
    @click="selectHandler"
  >
    <!-- @slot Use this slot to replace icon template. -->
    <slot
      name="icon"
      v-bind="{ iconAttrs: defaultProps.iconAttrs }"
    >
      <UiIcon
        v-bind="defaultProps.iconAttrs"
        class="ui-button__icon ui-tile__icon"
      />
    </slot>
    <!-- @slot Use this slot to replace label template. -->
    <slot
      name="label"
      v-bind="{ textLabelAttrs: defaultProps.textLabelAttrs }"
    >
      <UiText
        v-bind="defaultProps.textLabelAttrs"
        class="ui-tile__label"
      >
        <!-- @slot Use this slot to place content inside label. -->
        <slot />
      </UiText>
    </slot>
  </UiButton>
</template>

<script setup lang="ts">
import { uid } from 'uid/single';
import { computed } from 'vue';
import type { PropType } from 'vue';
import UiButton from '../../atoms/UiButton/UiButton.vue';
import UiText from '../../atoms/UiText/UiText.vue';
import UiIcon from '../../atoms/UiIcon/UiIcon.vue';
import type {
  Icon,
  IconAttrs,
} from '../../../types/icon';
import type { HTMLTag } from '../../../types/tag';

export type TileValue = string | Record<string, unknown>;
const props = defineProps({
  /**
   * Use this props or v-model to set checked.
   */
  modelValue: {
    type: [
      String,
      Object,
    ] as PropType<TileValue>,
    default: '',
  },
  /**
   * Use this props to set value of radio.
   */
  value: {
    type: [
      String,
      Object,
    ] as PropType<TileValue>,
    default: '',
  },
  /**
   * Use this props to set tile id
   * Default value is generated by uid i.e. `tile-<uid>`.
   */
  id: {
    type: String,
    default: '',
  },
  /**
   * Use this props to set icon.
   */
  icon: {
    type: [
      String,
      Object,
    ] as PropType<Icon>,
    default: '',
  },
  /**
   * Use this props to pass attrs for UiIcon
   */
  iconAttrs: {
    type: Object as PropType<IconAttrs>,
    default: () => ({}),
  },
  /**
   * Use this props to pass attrs for label UiText.
   */
  textLabelAttrs: {
    type: Object,
    default: () => ({ tag: 'span' }),
  },
});
interface DefaultProps {
  iconAttrs: {
    [key: string]: unknown
  },
  textLabelAttrs: {
    tag: HTMLTag,
    [key: string]: unknown
  }
}
const defaultProps = computed<DefaultProps>(() => ({
  iconAttrs: {
    ...{ icon: props.icon },
    ...props.iconAttrs,
  },
  textLabelAttrs: {
    tag: 'span',
    ...props.textLabelAttrs,
  },
}));
const emit = defineEmits<{(e: 'update:modelValue', value: TileValue): void}>();
const tileId = computed(() => (
  props.id || `tile-${uid()}`
));
const isChecked = computed(() => {
  if (typeof props.modelValue === 'string') {
    return props.value === props.modelValue;
  }
  return Object.keys(props.modelValue)
    .every((key: string) => (
      (props.modelValue as Record<string, unknown>)[key] === (props.value as Record<string, unknown>)[key]));
});
function selectHandler(): void {
  emit('update:modelValue', JSON.parse(JSON.stringify(props.value)));
}
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-tile {
  $this: &;
  $element: tile;

  --button-padding-block: #{functions.var($element, padding + "-block", var(--space-16))};
  --button-padding-inline: #{functions.var($element, padding + "-inline", var(--space-16))};
  --button-gap: #{functions.var($element, gap, var(--space-16))};

  align-items: center;
  justify-content: flex-start;
  transition:
    (
      background-color 150ms ease-in-out,
      border-color 150ms ease-in-out,
      color 150ms ease-in-out,
      transform 200ms ease,
    );

  &:active {
    transform: scale(0.95);
  }

  @include mixins.from-tablet {
    --button-padding-block: #{functions.var($element + "-tablet", padding + "-block", var(--space-24))};
    --button-padding-inline: #{functions.var($element + "-tablet", padding + "-inline", var(--space-16))};

    flex-direction: column;
  }

  &__icon {
    --icon-size: #{functions.var($element + "-icon", size, 3rem)};
    --button-icon-margin-block: 0;
    --button-icon-margin-inline: 0;

    @include mixins.from-tablet {
      --icon-size: #{functions.var($element + "-tablet-icon", size, 4rem)};
    }
  }

  &--small {
    #{$this}__icon {
      --icon-size: #{functions.var($element + "-icon", size, 2rem)};
    }
  }

  &--is-checked {
    --button-border-block-width: #{functions.var($element + "-checked", border-block-width, 2px)};
    --button-border-inline-width: #{functions.var($element + "-checked", border-inline-width, 2px)};
    --button-border-block-color:
      #{functions.var(
        $element + "-checked",
        border-inline-color,
        var(--color-border-strong)
      )};
    --button-border-inline-color:
      #{functions.var(
        $element + "-checked",
        border-block-color,
        var(--color-border-strong)
      )};
    --button-hover-border-block-color:
      #{functions.var(
        $element + "-hover-checked",
        border-block-color,
        var(--color-border-strong)
      )};
    --button-hover-border-inline-color:
      #{functions.var(
        $element + "-hover-checked",
        border-inline-color,
        var(--color-border-strong)
      )};
    --button-active-border-block-color:
      #{functions.var(
        $element + "-active-checked",
        border-block-color,
        var(--color-border-strong)
      )};
    --button-active-border-inline-color:
      #{functions.var(
        $element + "-active-checked",
        border-inline-color,
        var(--color-border-strong)
      )};
  }

  &--has-error {
    --button-border-block-color: var(--color-border-error-strong);
    --button-border-inline-color: var(--color-border-error-strong);
  }
}
</style>
