<template>
  <UiButton
    :id="tileId"
    :class="[
      'ui-button--outlined ui-tile', { 'ui-tile--is-checked': isChecked },
    ]"
    @click="selectHandler"
  >
    <!-- @slot Use this slot to replace icon template. -->
    <slot
      name="icon"
      v-bind="{ iconAttrs: defaultProps.iconAttrs }"
    >
      <UiIcon
        v-bind="defaultProps.iconAttrs"
        class="ui-button__icon ui-tile__icon"
      />
    </slot>
    <!-- @slot Use this slot to replace label template. -->
    <slot
      name="label"
      v-bind="{ textLabelAttrs: defaultProps.textLabelAttrs }"
    >
      <UiText
        v-bind="defaultProps.textLabelAttrs"
        class="ui-tile__label"
      >
        <!-- @slot Use this slot to place content inside label. -->
        <slot />
      </UiText>
    </slot>
  </UiButton>
</template>

<script setup lang="ts">
import { uid } from 'uid/single';
import { computed } from 'vue';
import UiButton from '../../atoms/UiButton/UiButton.vue';
import type { ButtonAttrsProps } from '../../atoms/UiButton/UiButton.vue';
import UiText from '../../atoms/UiText/UiText.vue';
import type { TextAttrsProps } from '../../atoms/UiText/UiText.vue';
import UiIcon from '../../atoms/UiIcon/UiIcon.vue';
import type { IconAttrsProps } from '../../atoms/UiIcon/UiIcon.vue';
import type { Icon } from '../../../types/icon';
import type { DefineAttrsProps } from '../../../types';

export type TileModelValue = string | Record<string, unknown>;
export interface TileProps {
  /**
   * Use this props or v-model to set checked.
   */
  modelValue?: TileModelValue;
  /**
   * Use this props to set value of radio.
   */
  value?: TileModelValue;
  /**
   * Use this props to set tile id
   * Default value is generated by uid i.e. `tile-<uid>`.
   */
  id?: string;
  /**
   * Use this props to set icon.
   */
  icon?: Icon;
  /**
   * Use this props to pass attrs for UiIcon
   */
  iconAttrs?: IconAttrsProps;
  /**
   * Use this props to pass attrs for label UiText.
   */
  textLabelAttrs?: TextAttrsProps;
}
export type TileAttrsProps = DefineAttrsProps<TileProps, ButtonAttrsProps>;
export interface TileEmits {
  (e: 'update:modelValue', value: TileModelValue): void;
}

const props = withDefaults(defineProps<TileProps>(), {
  modelValue: '',
  value: '',
  id: '',
  icon: '',
  iconAttrs: () => ({}),
  textLabelAttrs: () => ({ tag: 'span' }),
});
const defaultProps = computed(() => {
  const tag : TextAttrsProps['tag'] = 'span';
  return {
    iconAttrs: {
      icon: props.icon,
      ...props.iconAttrs,
    },
    textLabelAttrs: {
      tag,
      ...props.textLabelAttrs,
    },
  };
});
const emit = defineEmits<TileEmits>();
const tileId = computed(() => (
  props.id || `tile-${uid()}`
));
const isChecked = computed(() => {
  if (typeof props.modelValue === 'string') {
    return props.value === props.modelValue;
  }
  return Object.keys(props.modelValue)
    .every((key: string) => (
      (props.modelValue as Record<string, unknown>)[key] === (props.value as Record<string, unknown>)[key]));
});
const selectHandler = () => {
  emit('update:modelValue', JSON.parse(JSON.stringify(props.value)));
};
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-tile {
  $this: &;
  $element: tile;

  @include mixins.override-logical(button, $element, padding, var(--space-16));

  --button-gap: #{functions.var($element, gap, var(--space-16))};
  --border-radius-button: #{functions.var($element, border-radius, var(--border-radius-form))};

  align-items: center;
  justify-content: flex-start;
  transition:
    (
      background-color 150ms ease-in-out,
      border-color 150ms ease-in-out,
      color 150ms ease-in-out,
      transform 200ms ease,
    );

  &:active {
    transform: scale(0.95);
  }

  @include mixins.from-tablet {
    @include mixins.override-logical(button, $element + "-tablet", padding, var(--space-24) var(--space-16));

    flex-direction: column;
  }

  &__icon {
    @include mixins.override-logical(button-icon, null, margin, 0);

    --icon-size: #{functions.var($element + "-icon", size, 3rem)};

    @include mixins.from-tablet {
      --icon-size: #{functions.var($element + "-tablet-icon", size, 4rem)};
    }
  }

  &--small {
    #{$this}__icon {
      --icon-size: #{functions.var($element + "-icon", size, 2rem)};
    }
  }

  &--is-checked {
    @include mixins.override-logical(button, $element + "-checked", border-width, 2px);
    @include mixins.override-logical(button, $element + "-checked", border-color, var(--color-border-strong));
    @include mixins.override-logical(button-hover, $element + "-hover-checked", border-color, var(--color-border-strong));
    @include mixins.override-logical(button-active, $element + "-active-checked", border-color, var(--color-border-strong));
  }

  &--has-error {
    @include mixins.override-logical(button, null, border-color, var(--color-border-error-strong));
  }
}
</style>
