<template>
  <div
    class="ui-scale"
    role="radiogroup"
    :aria-label="defaultProps.translation.label"
  >
    <component
      :is="tag"
      class="ui-scale__controls"
    >
      <!-- @slot Use this slot to replace legend template. -->
      <slot
        name="legend"
        v-bind="{
          legend
        }"
      >
        <legend
          v-if="legend"
          class="visual-hidden"
        >
          {{ legend }}
        </legend>
      </slot>
      <template
        v-for="(_, index) in maxSteps"
        :key="index"
      >
        <UiRadio
          ref="optionRefs"
          v-model="scaleValue"
          :value="index"
          :name="scaleName"
          class="ui-scale__option"
          :aria-labelledby="`scale-label-${index}`"
          @mouseover="hoverHandler($event, index)"
          @mouseleave="hoverHandler($event, index)"
        >
          <template #radio>
            <div
              :style="calcActiveElementOpacity(index)"
              class="ui-scale__square"
              :class="{
                'ui-scale__square--is-checked': index <= finalValue,
              }"
            />
          </template>
          <template #label>
            <UiText
              :id="`scale-label-${index}`"
              tag="div"
              class="ui-scale__label"
              :class="{
                'ui-scale__label--is-checked': index === scaleValue,
              }"
            >
              {{ index + 1 }}
            </UiText>
          </template>
        </UiRadio>
      </template>
    </component>
    <div class="ui-scale__description">
      <UiText
        class="ui-scale__mild"
        aria-hidden="true"
      >
        {{ defaultProps.translation.mild }}
      </UiText>
      <UiText
        class="ui-scale__unbearable"
        aria-hidden="true"
      >
        {{ defaultProps.translation.unbearable }}
      </UiText>
    </div>
    <UiNumberStepper
      v-bind="proxyNumberStepperAttrs"
      class="ui-scale__mobile-controls"
      :model-value="scaleValue"
      :min="0"
      :max="steps - 1"
      @update:model-value="changeHandler"
    >
      <template
        v-for="(_, slotName) in $slots"
        #[slotName]="slotData"
      >
        <slot
          :name="slotName"
          v-bind="slotData"
        />
      </template>
    </UiNumberStepper>
  </div>
</template>

<script setup lang="ts">
import {
  computed,
  ref,
  useAttrs,
  watch,
} from 'vue';
import type {
  CSSProperties,
  PropType,
  ComponentPublicInstance,
} from 'vue';
import { uid } from 'uid/single';
import UiRadio from '../../atoms/UiRadio/UiRadio.vue';
import UiText from '../../atoms/UiText/UiText.vue';
import UiNumberStepper from '../UiNumberStepper/UiNumberStepper.vue';
import type { PropsAttrs } from '../../../types/attrs';
import { focusElement } from '../../../utilities/helpers/index.ts';
import type { HTMLTag } from '../../../types/tag';

export interface ScaleTranslation {
  label: string;
  mild: string;
  unbearable: string;
  [key: string]: string
}
const props = defineProps({
  /**
   * Use this props or v-model to set value.
   */
  modelValue: {
    type: Number,
    default: null,
  },
  /**
   * Use this props to set scale name.
   * Default value is generated by uid i.e. `scale-<uid>`.
   */
  name: {
    type: String,
    default: '',
  },
  /**
   * Use this props to set max value
   */
  steps: {
    type: Number,
    default: 10,
    validator: (value: number) => value > 0,
  },
  /**
   * Use this props to override labels inside component translation.
   */
  translation: {
    type: Object as PropType<ScaleTranslation>,
    default: () => ({
      label: 'Pain scale',
      mild: 'Mild',
      unbearable: 'Unbearable',
    }),
  },
  /**
   * Use this props to set scale tag.
   */
  tag: {
    type: String as PropType<HTMLTag>,
    default: 'fieldset',
  },
  /**
   * Use this props to set legend.
   */
  legend: {
    type: String,
    default: '',
  },
  /**
   * USe this props to pass attrs for UiNumberStepper
   */
  numberStepperAttrs: {
    type: Object as PropsAttrs,
    default: () => ({}),
  },
});
const defaultProps = computed(() => ({
  translation: {
    label: 'Pain scale',
    mild: 'Mild',
    unbearable: 'Unbearable',
    ...props.translation,
  },
}));
const emit = defineEmits<{(e: 'update:modelValue', value: number): void}>();
const scaleName = computed(() => (
  props.name || `scale-${uid()}`
));
const optionRefs = ref<ComponentPublicInstance[]>([]);
const maxSteps = computed(() => props.steps);
function valueValidation(value: number): boolean {
  return value >= 0 && value < maxSteps.value;
}
function changeHandler(value: number, modifier = 0): void {
  const newValue = value + modifier;
  if (valueValidation(newValue)) {
    emit('update:modelValue', newValue);
  }
}
const scaleValue = computed({
  get: (): number => props.modelValue,
  set: (value: number): void => {
    changeHandler(value);
  },
});
const hoverValue = ref(-1);
function hoverHandler({ type }: {type: string}, value: number): void {
  hoverValue.value = type === 'mouseover' ? value : -1;
}
const finalValue = computed(() => (hoverValue.value >= 0 ? hoverValue.value : scaleValue.value));
watch(finalValue, (value: number) => {
  focusElement(optionRefs.value[value]?.$el, true);
});
function calcActiveElementOpacity(index: number): CSSProperties {
  const opacityStepValue = 1 / (maxSteps.value - 1);
  const isActive = index <= finalValue.value;

  return isActive ? { '--_scale-square-overlay-opacity': (index * opacityStepValue).toFixed(3) } : {};
}
// TODO: remove in 0.6.0 / BEGIN
const attrs = useAttrs();
const buttonDecrementAttrs = computed(() => attrs.buttonDecrementAttrs || attrs['button-decrement-attrs']);
if (buttonDecrementAttrs.value) {
  if (process.env.NODE_ENV === 'development') {
    console.warn('[@infermedica/component-library warn][UiScale]: The `buttonDecrementAttrs` props will be removed in 0.6.0. Please use `numberStepperAttrs` props instead.');
  }
}
const buttonIncrementAttrs = computed(() => attrs.buttonIncrementAttrs || attrs['button-increment-attrs']);
if (buttonIncrementAttrs.value) {
  if (process.env.NODE_ENV === 'development') {
    console.warn('[@infermedica/component-library warn][UiScale]: The `buttonIncrementAttrs` will be removed in 0.6.0. Please use `numberStepperAttrs` props instead.');
  }
}
const proxyNumberStepperAttrs = computed(() => ({
  buttonDecrementAttrs: buttonDecrementAttrs.value,
  buttonIncrementAttrs: buttonIncrementAttrs.value,
  ...props.numberStepperAttrs,
}));
// END
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-scale {
  $this: &;
  $element: scale;

  &__controls {
    @at-root fieldset#{&} {
      padding: 0;
      border: none;
      margin: 0;
    }

    display: flex;
  }

  &__mobile-controls {
    margin: functions.var($element + "-mobile-controls", margin, var(--space-32) 0 0 0);

    @include mixins.from-tablet {
      display: none;
    }
  }

  &__option {
    --_scale-option-gap: #{functions.var($element + "-option", gap, 1px)};

    position: relative;
    flex: 1;
    flex-direction: column-reverse;
    align-items: center;
    border: solid transparent;
    border-width: 0 var(--_scale-option-gap) 0 0;
    border-radius: functions.var($element + "-option", border-radius, var(--border-radius-form));

    [dir="rtl"] & {
      border-width: 0 0 0 var(--_scale-option-gap);
    }

    &:first-of-type {
      #{$this}__square {
        border-radius: inherit;
        border-bottom-right-radius: 0;
        border-top-right-radius: 0;

        [dir="rtl"] & {
          border-radius: inherit;
          border-bottom-left-radius: 0;
          border-top-left-radius: 0;
        }
      }
    }

    &:last-of-type {
      --scale-option-gap: 0;

      #{$this}__square {
        border-radius: inherit;
        border-bottom-left-radius: 0;
        border-top-left-radius: 0;

        [dir="rtl"] & {
          border-radius: inherit;
          border-bottom-right-radius: 0;
          border-top-right-radius: 0;
        }
      }
    }

    &::after {
      position: absolute;
      z-index: 1;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      border-radius: inherit;
      box-shadow: var(--focus-outer);
      content: "";
      opacity: 0;
      pointer-events: none;
    }

    @include mixins.with-focus {
      &:focus-within {
        &::after {
          opacity: 1;
        }
      }
    }
  }

  &__square {
    position: relative;
    width: 100%;
    flex: 1 1 functions.var($element + "-square", height, 2.5rem);
    background: functions.var($element + "-square", background, var(--color-dataviz-diverging-track));

    &::after {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      background:
        functions.var(
          $element + "-square-overlay",
          background,
          var(--color-dataviz-diverging-strongly-negative)
        );
      border-radius: inherit;
      content: "";
      opacity: var(--_scale-square-overlay-opacity, 0);
      transition: opacity 150ms ease-in-out;
    }

    &--is-checked {
      background:
        functions.var(
          $element + "-square",
          background,
          var(--color-dataviz-diverging-moderately-negative)
        );
    }
  }

  &__label {
    --text-color: #{functions.var($element + "-label", color, var(--color-text-body))};

    position: relative;
    width: 100%;
    padding: functions.var($element + "-label", padding, var(--space-8) 0);
    margin: functions.var($element + "-label", margin, 0 0 var(--space-8) 0);
    border-radius: inherit;
    text-align: center;

    &::after {
      position: absolute;
      bottom: 0;
      left: 50%;
      width: functions.var($element + "-label-arrow", size, 8px);
      height: functions.var($element + "-label-arrow", size, 8px);
      background: inherit;
      content: "";
      transform: translate(-50%, 50%) rotate(45deg) scale(#{"calc(8 / 11.31)"});
    }

    &--is-checked {
      --text-color: #{functions.var($element + "-label", color, var(--color-text-on-selection))};

      background: functions.var($element + "-checked-label", background, var(--color-background-selection));
    }
  }

  &__description {
    --_scale-description-color: #{functions.var($element + "-description", color, var(--color-text-dimmed))};

    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: functions.var($element + "-description", margin, var(--space-16) 0 0 0);
  }

  &__mild {
    --text-color: #{functions.var($element + "-mild", color, var(--_scale-description-color))};
  }

  &__unbearable {
    --text-color: #{functions.var($element + "-unredable", color, var(--_scale-description-color))};
  }
}
</style>
