<template>
  <div
    class="ui-form-field"
  >
    <!-- @slot Use this slot to replace label template.-->
    <slot
      name="label"
      v-bind="{
        attrs: labelAttrs,
        label,
        hint,
        id: inputId
      }"
    >
      <UiText
        v-if="label"
        tag="label"
        :for="inputId"
        class="ui-form-field__label"
        v-bind="labelAttrs"
      >
        <UiText
          class="ui-text--body-2-comfortable ui-form-field__message"
          tag="span"
        >
          {{ label }}
        </UiText>
        <UiText
          v-if="hint"
          class="ui-text--body-2-comfortable ui-text--theme-secondary ui-form-field__hint"
          tag="span"
        >
          {{ hint }}
        </UiText>
      </UiText>
    </slot>
    <!-- @slot Use this slot to place input.-->
    <slot
      v-bind="{
        id: inputId
      }"
    />
    <!-- @slot Use this slot to replace alert template. -->
    <slot
      name="alert"
      v-bind="{
        attrs: alertAttrs,
        errorMessage
      }"
      :alert="alertAttrs"
    >
      <UiAlert
        v-if="errorMessage"
        v-bind="alertAttrs"
        class="ui-form-field__alert"
      >
        {{ errorMessage }}
      </UiAlert>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { uid } from 'uid/single';
import { computed } from 'vue';
import type { PropType } from 'vue';
import UiAlert from '../UiAlert/UiAlert.vue';
import UiText from '../../atoms/UiText/UiText.vue';
import type { PropsAttrs } from '../../../types/attrs';

const props = defineProps({
  /**
   * Use this props to set label $attrs
   */
  labelAttrs: {
    type: Object as PropsAttrs,
    default: () => ({
    }),
  },
  /**
   * Use this props to set label text
   */
  label: {
    type: [Boolean, String] as PropType<boolean | string>,
    default: false,
  },
  /**
   * Use this props to set input id and label for
   * Default value is generated by uid i.e. `input-<uid>`.
   */
  id: {
    type: String,
    default: '',
  },
  /**
   * Use this props to set label hint like "Required" or "Optional"
   */
  hint: {
    type: String,
    default: '',
  },
  /**
   * Use this props to set alert $attrs
   */
  alertAttrs: {
    type: Object as PropsAttrs,
    default: () => ({
    }),
  },
  /**
   * Use this props to set alert message
   */
  errorMessage: {
    type: [Boolean, String] as PropType<boolean | string>,
    default: '',
  },
});
const inputId = computed(() => (
  props.id || `input-${uid()}`
));
</script>

<style lang="scss">
@use "../../../styles/functions";

.ui-form-field {
  $element: form-field;

  &__label {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    margin: functions.var($element + "-label", margin, 0 0 var(--space-8) 0);
  }

  &__hint {
    margin: functions.var($element + "-hint", margin, 0 0 0 var(--space-8));

    [dir="rtl"] & {
      margin: functions.var($element + "-rtl-hint", margin, 0 var(--space-8) 0 0);
    }
  }

  &__alert {
    margin: functions.var($element + "-alert", margin, var(--space-8) 0 0 0);
  }
}
</style>
