<template>
  <div
    class="ui-form-field"
  >
    <!-- @slot Use this slot to replace label template.-->
    <slot
      name="label"
      v-bind="{
        message,
        hint,
        hasHint,
        id: inputId,
        textMessageAttrs: defaultProps.textMessageAttrs,
        textHintAttrs: defaultProps.textHintAttrs,
      }"
    >
      <label
        v-if="message"
        :for="inputId"
        class="ui-form-field__label"
      >
        <!-- @slot Use this slot to replace message template.-->
        <slot
          name="message"
          v-bind="{
            message,
            textMessageAttrs: defaultProps.textMessageAttrs
          }"
        >
          <UiText
            v-bind="defaultProps.textMessageAttrs"
            class="ui-text--body-2-comfortable ui-form-field__message"
          >
            {{ message }}
          </UiText>
        </slot>
        <!-- @slot Use this slot to replace hint template.-->
        <slot
          name="hint"
          v-bind="{
            hasHint,
            hint,
            textHintAttrs: defaultProps.textHintAttrs
          }"
        >
          <UiText
            v-if="hasHint"
            v-bind="defaultProps.textHintAttrs"
            class="ui-text--body-2-comfortable ui-text--theme-secondary ui-form-field__hint"
          >
            {{ hint }}
          </UiText>
        </slot>
      </label>
    </slot>
    <!-- @slot Use this slot to place input.-->
    <slot
      v-bind="{ id: inputId }"
    />
    <div class="ui-form-field__messages">
      <!-- @slot Use this slot to replace alert template. -->
      <slot
        name="alert"
        v-bind="{
          alertAttrs,
          hasErrorMessage,
          errorMessage,
        }"
      >
        <UiAlert
          v-if="hasErrorMessage"
          v-bind="alertAttrs"
          class="ui-form-field__alert"
        >
          {{ errorMessage }}
        </UiAlert>
      </slot>
      <slot
        name="character-counter"
        v-bind="{
          value,
          characterCounterAttrs,
          hasCharacterCounter,
          handleErrorEmit,
        }"
      >
        <UiFormFieldCharacterCounter
          v-if="hasCharacterCounter"
          v-bind="characterCounterAttrs"
          :value="value"
          @error="handleErrorEmit"
        />
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { uid } from 'uid/single';
import { computed } from 'vue';
import UiFormFieldCharacterCounter from './_internal/UiFormFieldCharacterCounter.vue';
import type { FormFieldCharacterCounterProps } from './_internal/UiFormFieldCharacterCounter.vue';
import UiAlert from '../UiAlert/UiAlert.vue';
import type { AlertAttrsProps } from '../UiAlert/UiAlert.vue';
import UiText from '../../atoms/UiText/UiText.vue';
import type { TextAttrsProps } from '../../atoms/UiText/UiText.vue';
import type { DefineAttrsProps } from '../../../types/attrs';

export interface FormFieldProps {
  /**
   * Use this props to set label text
   */
  message?: boolean | string;
  /**
   * Use this props to set input id and label for
   * Default value is generated by uid i.e. `input-<uid>`.
   */
  id?: string;
  /**
   * Use this props to set label hint like "Required" or "Optional"
   */
  hint?: boolean | string;
  /**
   * Use this props to pass value of input.
   */
  value?: string;
  /**
   * Use this props to show character counter.
   */
  hasCharacterCounter?: boolean;
  /**
   * Use this props to set alert message
   */
  errorMessage?: boolean | string;
  /**
   * Use this props to pass attrs to message UiText.
   */
  textMessageAttrs?: TextAttrsProps;
  /**
   * Use this props to pass attrs to hint UiText.
   */
  textHintAttrs?: TextAttrsProps;
  /**
   * Use this props to pass attrs to UiAlert.
   */
  alertAttrs?: AlertAttrsProps;
  characterCounterAttrs?: FormFieldCharacterCounterProps;
}
export type FormFieldAttrsProps = DefineAttrsProps<FormFieldProps>;
export interface FormFieldEmits {
  (e: 'error', value: string | null): void;
}
const emit = defineEmits<FormFieldEmits>();

const props = withDefaults(defineProps<FormFieldProps>(), {
  message: false,
  id: '',
  hint: false,
  errorMessage: false,
  hasCharacterCounter: false,
  textMessageAttrs: () => ({ tag: 'span' }),
  textHintAttrs: () => ({ tag: 'span' }),
  alertAttrs: () => ({}),
});
const defaultProps = computed(() => {
  const tag: TextAttrsProps['tag'] = 'span';
  return {
    textMessageAttrs: {
      tag,
      ...props.textMessageAttrs,
    },
    textHintAttrs: {
      tag,
      ...props.textHintAttrs,
    },
    characterCounterAttrs: {
      max: 240,
      ...props.characterCounterAttrs,
    },
  };
});
const inputId = computed(() => (
  props.id || `input-${uid()}`
));
const hasHint = computed(() => typeof props.hint !== 'boolean');
const hasErrorMessage = computed(() => typeof props.errorMessage !== 'boolean');
const handleErrorEmit = (error: string | null) => {
  emit('error', error);
};
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-form-field {
  $element: form-field;

  display: flex;
  flex-direction: column;
  gap: functions.var($element, gap, var(--space-8));

  &__label {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    gap: functions.var($element + "-label", gap, var(--space-8));
  }

  &__messages {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: var(--space-8);
  }

  &__character-counter {
    margin-inline: auto 0;
  }

  &--is-disabled {
    --text-color: var(--color-text-disabled);
  }
}
</style>
