<template>
  <div
    class="ui-form-field"
  >
    <!-- @slot Use this slot to replace label template.-->
    <slot
      name="label"
      v-bind="{
        label,
        message,
        hint,
        id: inputId,
        textMessageAttrs: defaultProps.textMessageAttrs,
        textHintAttrs: defaultProps.textHintAttrs,
      }"
    >
      <label
        v-if="label || message"
        :for="inputId"
        class="ui-form-field__label"
      >
        <!-- @slot Use this slot to replace message template.-->
        <slot
          name="message"
          v-bind="{
            label,
            message,
            textMessageAttrs: defaultProps.textMessageAttrs
          }"
        >
          <UiText
            v-bind="defaultProps.textMessageAttrs"
            class="ui-text--body-2-comfortable ui-form-field__message"
          >
            {{ label || message }}
          </UiText>
        </slot>
        <!-- @slot Use this slot to replace hint template.-->
        <slot
          name="hint"
          v-bind="{
            hint,
            textHintAttrs: defaultProps.textHintAttrs
          }"
        >
          <UiText
            v-if="hint"
            v-bind="defaultProps.textHintAttrs"
            class="ui-text--body-2-comfortable ui-text--theme-secondary ui-form-field__hint"
          >
            {{ hint }}
          </UiText>
        </slot>
      </label>
    </slot>
    <!-- @slot Use this slot to place input.-->
    <slot
      v-bind="{ id: inputId }"
    />
    <!-- @slot Use this slot to replace alert template. -->
    <slot
      name="alert"
      v-bind="{
        alertAttrs,
        errorMessage
      }"
    >
      <UiAlert
        v-if="errorMessage"
        v-bind="alertAttrs"
        class="ui-form-field__alert"
      >
        {{ errorMessage }}
      </UiAlert>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { uid } from 'uid/single';
import {
  computed,
  useAttrs,
} from 'vue';
import type { PropType } from 'vue';
import UiAlert from '../UiAlert/UiAlert.vue';
import UiText from '../../atoms/UiText/UiText.vue';
import type { PropsAttrs } from '../../../types/attrs';
import type { HTMLTag } from '../../../types/tag';

const props = defineProps({
  /**
   * Use this props to set label text
   */
  message: {
    type: [
      Boolean,
      String,
    ] as PropType<boolean | string>,
    default: false,
  },
  /**
   * Use this props to set input id and label for
   * Default value is generated by uid i.e. `input-<uid>`.
   */
  id: {
    type: String,
    default: '',
  },
  /**
   * Use this props to set label hint like "Required" or "Optional"
   */
  hint: {
    type: [
      Boolean,
      String,
    ] as PropType<boolean | string>,
    default: '',
  },
  /**
   * Use this props to set alert message
   */
  errorMessage: {
    type: [
      Boolean,
      String,
    ] as PropType<boolean | string>,
    default: '',
  },
  /**
   * Use this props to pass attrs to message UiText.
   */
  textMessageAttrs: {
    type: Object as PropsAttrs,
    default: () => ({ tag: 'span' }),
  },
  /**
   * Use this props to pass attrs to hint UiText.
   */
  textHintAttrs: {
    type: Object as PropsAttrs,
    default: () => ({ tag: 'span' }),
  },
  /**
   * Use this props to pass attrs to UiAlert.
   */
  alertAttrs: {
    type: Object as PropsAttrs,
    default: () => ({}),
  },
});
const defaultProps = computed(() => ({
  textMessageAttrs: {
    tag: 'span' as HTMLTag,
    ...props.textMessageAttrs,
  },
  textHintAttrs: {
    tag: 'span' as HTMLTag,
    ...props.textHintAttrs,
  },
}));
const inputId = computed(() => (
  props.id || `input-${uid()}`
));
// TODO: remove in 0.6.0 / BEGIN
const attrs = useAttrs();
const labelAttrs = computed(() => attrs.labelAttrs || attrs['label-attrs']);
if (labelAttrs.value) {
  if (process.env.NODE_ENV === 'development') {
    console.warn('[@infermedica/component-library warn][UiFormField]: The `labelAttrs` will be removed in 0.6.0.');
  }
}
const label = computed(() => attrs.label);
if (label.value) {
  if (process.env.NODE_ENV === 'development') {
    console.warn('[@infermedica/component-library warn][UiFormField]: The `label` props will be removed in 0.6.0. Please use `message` props instead.');
  }
}
// END
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-form-field {
  $element: form-field;

  display: flex;
  flex-direction: column;
  gap: functions.var($element, gap, var(--space-8));

  &__label {
    display: flex;
    align-items: center;
    justify-content: flex-start;
    gap: functions.var($element + "label", gap, var(--space-8))
  }
}
</style>
