<template>
  <label
    class="ui-checkbox"
    :for="checkboxId"
    v-bind="{
      ...attrs,
      ...elementsListeners.label
    }"
  >
    <input
      :id="checkboxId"
      v-keyboard-focus
      v-bind="defaultProps.inputAttrs"
      :checked="isChecked"
      type="checkbox"
      class="visual-hidden"
      @change="changeHandler($event)"
    >
    <!-- @slot Use this slot to replace checkbox template.-->
    <slot
      :name="checkbutton && 'checkbutton' || 'checkbox'"
      v-bind="{
        checked: isChecked,
        iconCheckmarkAttrs: defaultProps.iconCheckmarkAttrs
      }"
    >
      <div
        class="ui-checkbox__checkbox"
        :class="{ 'ui-checkbox__checkbox--is-checked': isChecked, }"
      >
        <!-- @slot Use this slot to replace checkmark template.-->
        <slot
          name="checkmark"
          v-bind="{ iconCheckmarkAttrs: defaultProps.iconCheckmarkAttrs }"
        >
          <UiIcon
            v-bind="defaultProps.iconCheckmarkAttrs"
            class="ui-checkbox__checkmark"
          />
        </slot>
      </div>
    </slot>
    <!-- @slot Use this slot to replace label template. -->
    <slot
      name="label"
      v-bind="{
        hasLabel,
        textLabelAttrs: defaultProps.textLabelAttrs
      }"
    >
      <UiText
        v-if="hasLabel"
        v-bind="defaultProps.textLabelAttrs"
        class="ui-checkbox__label"
      >
        <!-- @slot Use this slot to place content inside label. -->
        <slot />
      </UiText>
    </slot>
  </label>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import {
  computed,
  useSlots,
  type LabelHTMLAttributes,
  type InputHTMLAttributes,
} from 'vue';
import equal from 'fast-deep-equal';
import { uid } from 'uid/single';
import type { DefineAttrs } from '../../../types/attrs';
import UiIcon, { type IconAttrs } from '../UiIcon/UiIcon.vue';
import UiText, { type TextAttrs } from '../UiText/UiText.vue';
import useAttributes from '../../../composable/useAttributes';
import { keyboardFocus as vKeyboardFocus } from '../../../utilities/directives';

export interface CheckboxProps {
  /**
   *  Use this props or v-model to set checked.
   */
  modelValue?: boolean | Record<string, unknown>[];
  /**
   * Use this props to set value of checkbox.
   * Required for multiple checkboxes.
   */
  value?: string | Record<string, unknown>;
  /**
   * Use this props to set checkbox id.
   * Default value is generated by uid i.e. `checkbox-<uid>`.
   */
  id?: string;
  /**
   * Use this props to disabled checkbox.
   * Remember to use `ui-checkbox--is-disabled` class to style disabled checkbox.
   */
  disabled?: boolean;
  /**
   * Use this props to pass attrs for input element.
   */
  inputAttrs?: DefineAttrs<InputHTMLAttributes>;
  /**
   * Use this props to pass attrs for checkmark UiIcon
   */
  iconCheckmarkAttrs?: IconAttrs;
  /**
   * Use this props to pass attrs for label UiText
   */
  textLabelAttrs?: TextAttrs;
}
export type CheckboxAttrs = DefineAttrs<CheckboxProps, LabelHTMLAttributes>;
const props = withDefaults(defineProps<CheckboxProps>(), {
  modelValue: false,
  value: '',
  id: '',
  disabled: false,
  inputAttrs: () => ({}),
  iconCheckmarkAttrs: () => ({ icon: 'checkmark' }),
  textLabelAttrs: () => ({ tag: 'span' }),
});
const {
  attrs, listeners,
} = useAttributes<LabelHTMLAttributes>();
const elementsListeners = computed(() => {
  const {
    onFocus, onBlur, ...rest
  } = listeners.value;
  return {
    input: {
      onFocus,
      onBlur,
    },
    label: rest,
  };
});
const defaultProps = computed(() => ({
  iconCheckmarkAttrs: {
    icon: 'checkmark' as IconAttrs['icon'],
    ...props.iconCheckmarkAttrs,
  },
  textLabelAttrs: {
    tag: 'span' as TextAttrs['tag'],
    ...props.textLabelAttrs,
  },
  inputAttrs: {
    disabled: props.disabled,
    ...elementsListeners.value.input,
    ...props.inputAttrs,
  },
}));
const emit = defineEmits<{(e: 'update:modelValue', value: CheckboxAttrs['modelValue']): void
}>();
const slots = useSlots();
const hasLabel = computed(() => (!!slots.default));
const checkboxId = computed(() => (props.id || `checkbox-${uid()}`));
const isChecked = computed(() => {
  if (Array.isArray(props.modelValue)) {
    return !!props.modelValue.find((option) => (
      equal(JSON.parse(JSON.stringify(props.value)), JSON.parse(JSON.stringify(option)))));
  }
  return props.modelValue;
});
const getChecked = (checked: boolean): CheckboxAttrs['modelValue'] => {
  if (Array.isArray(props.modelValue)) {
    return checked
      ? [
        ...props.modelValue,
        JSON.parse(JSON.stringify(props.value)),
      ]
      : props.modelValue.filter((option) => (!equal(props.value, option)));
  }
  return checked;
};
function changeHandler(event: Event): void {
  const el = event.target as HTMLInputElement;
  emit('update:modelValue', getChecked(el.checked));
}

// TODO: remove in 0.6.0 / BEGIN
const checkbutton = computed(() => (slots.checkbutton));
if (checkbutton.value) {
  if (process.env.NODE_ENV === 'development') {
    console.warn('[@infermedica/component-library warn][UiCheckbox]: The `checkbutton` slot will be removed in 0.6.0. Please use `checkbox` slot instead.');
  }
}
// END
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-checkbox {
  $this: &;
  $element: checkbox;

  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  gap: functions.var($element, gap, var(--space-12));

  @include mixins.with-hover {
    cursor: pointer;
  }

  @include mixins.hover {
    #{$this}__checkbox {
      &::after {
        @include mixins.use-logical($element + "-hover", border-color, var(--color-border-strong-hover));
      }

      &--is-checked {
        background:
          functions.var(
            $element + "-checked-hover",
            background,
            var(--color-selectioncontrols-selection-hover)
          );

        &::after {
          border-color:
            functions.var(
              $element + "-checked-hover",
              border-color,
              var(--color-selectioncontrols-selection-hover)
            );
        }
      }
    }
  }

  &:active {
    #{$this}__checkbox {
      &::after {
        @include mixins.use-logical($element + "-active", border-color, var(--color-border-strong-active));
      }

      &--is-checked {
        background:
          functions.var(
            $element + "-checked-active",
            background,
            var(--color-selectioncontrols-selection-active)
          );

        &::after {
          @include mixins.use-logical(
            $element + "-checked-active",
            border-color,
            var(--color-selectioncontrols-selection-active)
          );
        }
      }
    }
  }

  @include mixins.with-focus {
    &:focus-within {
      #{$this}__checkbox {
        box-shadow: var(--focus-outer);
      }
    }
  }

  &__checkbox {
    @include mixins.inner-border(
      $element,
      $color: var(--color-border-strong),
      $width: 2px,
      $radius: var(--border-radius-form),
      $transition: (
        border-color 150ms ease-in-out,
        background-color 150ms ease-in-out
      )
    );
    @include mixins.use-logical($element + "-checkbox", margin, var(--space-2));

    display: flex;
    width: functions.var($element, size, 1.25rem);
    height: functions.var($element, size, 1.25rem);
    flex: none;
    align-items: center;
    justify-content: center;
    background: functions.var($element, background, var(--color-background-white));

    &--is-checked {
      background: functions.var($element + "-checked", background, var(--color-selectioncontrols-selection));

      &::after {
        @include mixins.use-logical($element + "-checked", border-color, var(--color-selectioncontrols-selection));
      }

      #{$this}__checkmark {
        --icon-color: #{functions.var($element + "-checked-checkmark", color, var(--color-text-on-selection))};
      }
    }
  }

  &__checkmark {
    --icon-size: #{functions.var($element + "-checkmark", size, 1rem)};
    --icon-color: #{functions.var($element + "-checkmark", color, transparent)};

    flex: none;
  }

  &__label {
    --text-margin: #{functions.var($element + "-label", margin, 0 0 0 var(--space-12))};
    --text-color: #{functions.var($element + "-label", color, var(--color-text-body))};

    flex: 1;
  }

  &--is-disabled {
    cursor: not-allowed;

    @include mixins.hover {
      #{$this}__checkbox {
        &::after {
          @include mixins.use-logical($element + "-hover", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          background: functions.var($element + "-checked-hover", background, var(--color-icon-disabled));

          &::after {
            @include mixins.use-logical($element + "-checked-hover", border-color, var(--color-icon-disabled));
          }
        }
      }
    }

    &:active {
      #{$this}__checkbox {
        &::after {
          @include mixins.use-logical($element + "-hover", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          background: functions.var($element + "-checked-active", background, var(--color-icon-disabled));

          &::after {
            @include mixins.use-logical($element + "-checked-active", border-color, var(--color-icon-disabled));
          }
        }
      }
    }

    #{$this}__checkbox {
      &::after {
        @include mixins.use-logical($element, border-color, var(--color-icon-disabled));
      }

      &--is-checked {
        background: functions.var($element + "-checked", background, var(--color-icon-disabled));

        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-icon-disabled));
        }
      }
    }

    #{$this}__label {
      --text-color: #{functions.var($element + "-label", color, var(--color-text-disabled))};
    }
  }

  &--has-error {
    @include mixins.hover {
      #{$this}__checkbox {
        &::after {
          @include mixins.use-logical($element + "-hover", border-color, var(--color-border-error-strong-hover));
        }

        &--is-checked {
          background: functions.var($element + "-checked-hover", background, var(--color-border-error-strong-hover));

          &::after {
            @include mixins.use-logical(
              $element + "-checked-hover",
              border-color,
              var(--color-border-error-strong-hover)
            );
          }
        }
      }
    }

    &:active {
      #{$this}__checkbox {
        &::after {
          @include mixins.use-logical($element + "-hover", border-color, var(--color-border-error-strong-hover));
        }

        &--is-checked {
          background: functions.var($element + "-checked-active", background, var(--color-border-error-strong-active));

          &::after {
            @include mixins.use-logical(
              $element + "-checked-active",
              border-color,
              var(--color-border-error-strong-active)
            );
          }
        }
      }
    }

    #{$this}__checkbox {
      &::after {
        @include mixins.use-logical($element, border-color, var(--color-border-error-strong));
      }

      &--is-checked {
        background: functions.var($element + "-checked", background, var(--color-border-error-strong));

        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-border-error-strong));
        }
      }
    }
  }
}
</style>
