<template>
  <label
    class="ui-checkbox"
    :for="checkboxId"
    v-bind="getRootAttrs($attrs)"
  >
    <input
      :id="checkboxId"
      v-keyboard-focus
      v-bind="getInputAttrs($attrs)"
      :checked="isChecked"
      type="checkbox"
      class="visual-hidden"
      @change="changeHandler($event)"
    >
    <!-- @slot Use this slot to replace checkbox template.-->
    <slot
      name="checkbox"
      v-bind="{
        checked: isChecked,
        iconCheckmarkAttrs: defaultProps.iconCheckmarkAttrs
      }"
    >
      <div
        class="ui-checkbox__checkbox"
        :class="{
          'ui-checkbox__checkbox--is-checked': isChecked,
        }"
      >
        <!-- @slot Use this slot to replace checkmark template.-->
        <slot
          name="checkmark"
          v-bind="{
            attrs: defaultProps.iconCheckmarkAttrs
          }"
        >
          <UiIcon
            v-bind="defaultProps.iconCheckmarkAttrs"
            class="ui-checkbox__checkmark"
          />
        </slot>
      </div>
    </slot>
    <!-- @slot Use this slot to replace label template. -->
    <slot
      name="label"
      v-bind="{
        hasLabel,
        attrs: defaultProps.textLabelAttrs
      }"
    >
      <UiText
        v-if="hasLabel"
        v-bind="defaultProps.textLabelAttrs"
        class="ui-checkbox__label"
      >
        <!-- @slot Use this slot to place content inside label. -->
        <slot />
      </UiText>
    </slot>
  </label>
</template>

<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>

<script setup lang="ts">
import {
  computed,
  useSlots,
} from 'vue';
import type { PropType } from 'vue';
import equal from 'fast-deep-equal';
import { uid } from 'uid/single';
import UiIcon from '../UiIcon/UiIcon.vue';
import UiText from '../UiText/UiText.vue';
import useInput from '../../../composable/useInput';
import { keyboardFocus as vKeyboardFocus } from '../../../utilities/directives';

export type CheckboxValue = string | object;
export type CheckboxModelValue = boolean | object[];
const props = defineProps({
  /**
   *  Use this props or v-model to set checked.
   */
  modelValue: {
    type: [Boolean, Array] as PropType<CheckboxModelValue>,
    default: false,
  },
  /**
   * Use this props to set value of checkbox.
   * Required for multiple checkboxes.
   */
  value: {
    type: [String, Object] as PropType<CheckboxValue>,
    default: '',
  },
  /**
   * Use this props to set checkbox id.
   * Default value is generated by uid i.e. `checkbox-<uid>`.
   */
  id: {
    type: String,
    default: '',
  },
  /**
   * Use this props to pass attrs for checkmark UiIcon
   */
  iconCheckmarkAttrs: {
    type: Object,
    default: () => ({
      icon: 'checkmark',
    }),
  },
  /**
   * Use this props to pass attrs for label UiText
   */
  textLabelAttrs: {
    type: Object,
    default: () => ({
      tag: 'span',
    }),
  },
});
const defaultProps = computed(() => ({
  iconCheckmarkAttrs: {
    icon: 'checkmark',
    ...props.iconCheckmarkAttrs,
  },
  textLabelAttrs: {
    tag: 'span',
    ...props.textLabelAttrs,
  },
}));
const emit = defineEmits<{(e: 'update:modelValue', value: boolean | object[]): void
}>();
const slots = useSlots();
const {
  getRootAttrs, getInputAttrs,
} = useInput();
const hasLabel = computed(() => (!!slots.default));
const checkboxId = computed(() => (props.id || `checkbox-${uid()}`));
const isChecked = computed(() => {
  if (Array.isArray(props.modelValue)) {
    return !!props.modelValue.find((option: object) => (
      equal(JSON.parse(JSON.stringify(props.value)), JSON.parse(JSON.stringify(option)))));
  }
  return props.modelValue;
});
const getChecked = (checked: boolean): CheckboxModelValue => {
  if (Array.isArray(props.modelValue)) {
    return checked
      ? [...props.modelValue, JSON.parse(JSON.stringify(props.value))]
      : props.modelValue.filter((option: object) => (!equal(props.value, option)));
  }
  return checked;
};
function changeHandler(event: Event): void {
  const el = event.target as HTMLInputElement;
  emit('update:modelValue', getChecked(el.checked));
}

// TODO: remove in 0.6.0 / BEGIN
const {
  checkbutton,
} = slots;
if (checkbutton) {
  throw new Error('[@infermedica/component-library error][UiCheckbox]: The `checkbotton` slot is deprecated and removed. Please use `checkbox` slot instead.');
}
// END
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-checkbox {
  $this: &;
  $element: checkbox;

  display: flex;
  align-items: flex-start;
  justify-content: flex-start;

  @include mixins.with-hover {
    cursor: pointer;
  }

  @include mixins.hover {
    #{$this}__checkbox {
      &::after {
        border-color: functions.var($element + "-hover", border-color, var(--color-border-strong-hover));
      }

      &--is-checked {
        background: functions.var($element + "-checked-hover", background, var(--color-selectioncontrols-selection-hover));

        &::after {
          border-color:
            functions.var(
              $element + "-checked-hover",
              border-color,
              var(--color-selectioncontrols-selection-hover)
            );
        }
      }
    }
  }

  &:active {
    #{$this}__checkbox {
      &::after {
        border-color: functions.var($element + "-active", border-color, var(--color-border-strong-active));
      }

      &--is-checked {
        background:
          functions.var(
            $element + "-checked-active",
            background,
            var(--color-selectioncontrols-selection-active)
          );

        &::after {
          border-color:
            functions.var(
              $element + "-checked-active",
              border-color,
              var(--color-selectioncontrols-selection-active)
            );
        }
      }
    }
  }

  @include mixins.with-focus {
    &:focus-within {
      #{$this}__checkbox {
        box-shadow: var(--focus-outer);
      }
    }
  }

  &__checkbox {
    @include mixins.inner-border(
      $element,
      $color: var(--color-border-strong),
      $width: 2px,
      $radius: var(--border-radius-form),
      $transition: (
        border-color 150ms ease-in-out,
        background-color 150ms ease-in-out
      )
    );

    display: flex;
    width: functions.var($element, size, 1.25rem);
    height: functions.var($element, size, 1.25rem);
    flex: none;
    align-items: center;
    justify-content: center;
    margin: 2px;
    background: functions.var($element, background, var(--color-background-white));

    &--is-checked {
      background: functions.var($element + "-checked", background, var(--color-selectioncontrols-selection));

      &::after {
        border-color: functions.var($element + "-checked", border-color, var(--color-selectioncontrols-selection));
      }

      #{$this}__checkmark {
        --icon-color: #{functions.var($element + "-checked-checkmark", color, var(--color-text-on-selection))};
      }
    }
  }

  &__checkmark {
    --icon-size: #{functions.var($element + "-checkmark", size, 1rem)};
    --icon-color: #{functions.var($element + "-checkmark", color, transparent)};

    flex: none;
  }

  &__label {
    --text-color: #{functions.var($element + "-label", color, var(--color-text-body))};

    flex: 1;
    margin: functions.var($element + "-label", margin, 0 0 0 var(--space-12));

    [dir="rtl"] & {
      margin: functions.var($element + "-rtl-label", margin, 0 var(--space-12) 0 0);
    }
  }

  &--is-disabled {
    cursor: not-allowed;

    @include mixins.hover {
      #{$this}__checkbox {
        &::after {
          border-color: functions.var($element + "-hover", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          background: functions.var($element + "-checked-hover", background, var(--color-icon-disabled));

          &::after {
            border-color: functions.var($element + "-checked-hover", border-color, var(--color-icon-disabled));
          }
        }
      }
    }

    &:active {
      #{$this}__checkbox {
        &::after {
          border-color: functions.var($element + "-hover", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          background: functions.var($element + "-checked-active", background, var(--color-icon-disabled));

          &::after {
            border-color: functions.var($element + "-checked-active", border-color, var(--color-icon-disabled));
          }
        }
      }
    }

    #{$this}__checkbox {
      &::after {
        border-color: functions.var($element, border-color, var(--color-icon-disabled));
      }

      &--is-checked {
        background: functions.var($element + "-checked", background, var(--color-icon-disabled));

        &::after {
          border-color: functions.var($element + "-checked", border-color, var(--color-icon-disabled));
        }
      }
    }

    #{$this}__label {
      --text-color: #{functions.var($element + "-label", color, var(--color-text-disabled))};
    }
  }

  &--has-error {
    @include mixins.hover {
      #{$this}__checkbox {
        &::after {
          border-color: functions.var($element + "-hover", border-color, var(--color-border-error-strong-hover));
        }

        &--is-checked {
          background: functions.var($element + "-checked-hover", background, var(--color-border-error-strong-hover));

          &::after {
            border-color: functions.var($element + "-checked-hover", border-color, var(--color-border-error-strong-hover));
          }
        }
      }
    }

    &:active {
      #{$this}__checkbox {
        &::after {
          border-color: functions.var($element + "-hover", border-color, var(--color-border-error-strong-hover));
        }

        &--is-checked {
          background: functions.var($element + "-checked-active", background, var(--color-border-error-strong-active));

          &::after {
            border-color: functions.var($element + "-checked-active", border-color, var(--color-border-error-strong-active));
          }
        }
      }
    }

    #{$this}__checkbox {
      &::after {
        border-color: functions.var($element, border-color, var(--color-border-error-strong));
      }

      &--is-checked {
        background: functions.var($element + "-checked", background, var(--color-border-error-strong));

        &::after {
          border-color: functions.var($element + "-checked", border-color, var(--color-border-error-strong));
        }
      }
    }
  }
}
</style>
