<template>
  <label
    class="ui-radio"
    :for="radioId"
    v-bind="getRootAttrs($attrs)"
  >
    <input
      :id="radioId"
      v-keyboard-focus
      type="radio"
      class="visual-hidden"
      :checked="isChecked"
      v-bind="getInputAttrs($attrs)"
      @change="changeHandler($event)"
    >
    <!-- @slot Use this slot to replace radiobutton template. -->
    <slot
      name="radiobutton"
    >
      <div
        class="ui-radio__radiobutton"
      >
        <div
          class="ui-radio__mark"
        />
      </div>
    </slot>
    <!-- @slot Use this slot to replace label template. -->
    <slot name="label">
      <UiText
        v-if="hasLabel"
        tag="span"
        class="ui-radio__label"
      >
        <!-- @slot Use this slot to place content inside label. -->
        <slot />
      </UiText>
    </slot>
  </label>
</template>

<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>

<script setup lang="ts">
import { computed, useSlots } from 'vue';
import type { PropType } from 'vue';
import equal from 'fast-deep-equal';
import { uid } from 'uid/single';
import UiText from '../UiText/UiText.vue';
import useInput from '../../../composable/useInput';
import { keyboardFocus as vKeyboardFocus } from '../../../utilities/directives';

export type RadioValue = number | string | Record<string, unknown>;
const props = defineProps({
  /**
   * Use this props to set radio id
   * Default value is generated by uid i.e. `radio-<uid>`.
   */
  id: {
    type: String,
    default: '',
  },
  /**
   * Use this props to set value of radio.
   */
  value: {
    type: [Number, String, Object] as PropType<RadioValue>,
    default: '',
  },
  /**
   * Use this props or v-model to set checked.
   */
  modelValue: {
    type: [Number, String, Object] as PropType<RadioValue>,
    default: '',
  },
});
const emit = defineEmits<{(e: 'update:modelValue', value: RadioValue): void
}>();
const slots = useSlots();
const hasLabel = computed(() => (!!slots.default));
const radioId = computed(() => (
  props.id || `radio-${uid()}`
));
const isChecked = computed(() => (equal(
  JSON.parse(JSON.stringify(props.value)),
  JSON.parse(JSON.stringify(props.modelValue)),
)));
const { getRootAttrs, getInputAttrs } = useInput();
function changeHandler(event: Event) {
  const el = event.target as HTMLInputElement;
  if (el.checked) {
    emit('update:modelValue', JSON.parse(JSON.stringify(props.value)));
  }
}
</script>

<style lang="scss">
@import "../../../styles/mixins/mixins";

.ui-radio {
  $this: &;

  display: inline-flex;
  cursor: pointer;

  @media (hover: hover) {
    &:hover {
      --radio-border: solid var(--color-border-strong-hover);
    }
  }

  &:active {
    --radio-border: solid var(--color-border-strong-active);
  }

  &__radiobutton {
    @include inner-border($element: radio, $width: 2px, $radius: var(--border-radius-circle));

    display: flex;
    overflow: hidden;
    width: var(--radio-size, 1.25rem);
    height: var(--radio-size, 1.25rem);
    flex: none;
    align-items: center;
    justify-content: center;
    margin: var(--radio-margin, 0.125rem);
    background: var(--radio-background, var(--color-background-white));
  }

  &__mark {
    width: var(--radio-mark-size, 0.625rem);
    height: var(--radio-mark-size, 0.625rem);
    flex: none;
    background: var(--radio-mark-background, transparent);
    border-radius: var(--border-radius-circle);
  }

  input {
    &:checked {
      & + #{$this}__radiobutton {
        --radio-border: solid var(--color-selectioncontrols-selection);
        --radio-mark-background: var(--color-selectioncontrols-selection);
      }

      @media (hover: hover) {
        &:hover + #{$this}__radiobutton {
          --radio-border: solid var(--color-selectioncontrols-selection-hover);
          --radio-mark-background: var(--color-selectioncontrols-selection-hover);
        }
      }

      &:active + #{$this}__radiobutton {
        --radio-border: solid var(--color-selectioncontrols-selection-active);
        --radio-mark-background: var(--color-selectioncontrols-selection-active);
      }
    }

    @include focus {
      & + #{$this}__radiobutton {
        box-shadow: var(--focus-outer);
      }
    }
  }

  &__label {
    @include font(radio-label, body-1, text);

    flex: var(--radio-label-flex, 1);
    margin: var(--radio-label-margin, 0 0 0 var(--space-12));
    color: var(--radio-label-color, var(--color-text-body));

    [dir="rtl"] & {
      margin: var(--radio-label-margin, 0 var(--space-12) 0 0);
    }
  }

  &--is-disabled {
    --radio-border: solid var(--color-border-subtle);

    cursor: not-allowed;

    @media (hover: hover) {
      &:hover {
        --radio-border: solid var(--color-border-subtle);
      }
    }

    &:active {
      --radio-border: solid var(--color-border-subtle);
    }

    input:checked {
      & + #{$this}__radiobutton,
      &:active + #{$this}__radiobutton {
        --radio-border: solid var(--color-border-subtle);
        --radio-mark-background: var(--color-border-subtle);
      }

      @media (hover: hover) {
        &:hover + #{$this}__radiobutton {
          --radio-border: solid var(--color-border-subtle);
          --radio-mark-background: var(--color-border-subtle);
        }
      }
    }
  }

  &--has-error {
    --radio-border: solid var(--color-border-error-strong);

    @media (hover: hover) {
      &:hover {
        --radio-border: solid var(--color-border-error-strong);
      }
    }

    &:active {
      --radio-border: solid var(--color-border-error-strong);
    }

    input:checked {
      & + #{$this}__radiobutton,
      &:active + #{$this}__radiobutton {
        --radio-border: solid var(--color-border-error-strong);
        --radio-mark-background: var(--color-border-error-strong);
      }

      @media (hover: hover) {
        &:hover + #{$this}__radiobutton {
          --radio-border: solid var(--color-border-error-strong);
          --radio-mark-background: var(--color-border-error-strong);
        }
      }
    }
  }
}
</style>
