<template>
  <label
    class="ui-radio"
    :for="radioId"
    v-bind="{
      ...attrs,
      ...elementsListeners.label
    }"
  >
    <input
      :id="radioId"
      v-keyboard-focus
      type="radio"
      class="visual-hidden"
      :checked="isChecked"
      v-bind="defaultProps.inputAttrs"
      @change="changeHandler($event)"
    >
    <!-- @slot Use this slot to replace radiobutton template. -->
    <slot
      :name="radiobutton && 'radiobutton' || 'radio'"
      v-bind="{
        checked: isChecked,
        radioElementAttrs,
      }"
    >
      <div
        v-bind="radioElementAttrs"
        :class="[
          'ui-radio__radio',{ 'ui-radio__radio--is-checked': isChecked }
        ]"
      >
        <div class="ui-radio__mark" />
      </div>
    </slot>
    <!-- @slot Use this slot to replace label template. -->
    <slot
      name="label"
      v-bind="{
        hasLabel,
        textLabelAttrs: defaultProps.textLabelAttrs
      }"
    >
      <UiText
        v-if="hasLabel"
        v-bind="defaultProps.textLabelAttrs"
        class="ui-radio__label"
      >
        <!-- @slot Use this slot to place content inside label. -->
        <slot />
      </UiText>
    </slot>
  </label>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import {
  computed,
  useSlots,
} from 'vue';
import type {
  HTMLAttributes,
  InputHTMLAttributes,
  LabelHTMLAttributes,
} from 'vue';
import equal from 'fast-deep-equal';
import { uid } from 'uid/single';
import useAttributes from '../../../composable/useAttributes';
import { keyboardFocus as vKeyboardFocus } from '../../../utilities/directives';
import UiText from '../UiText/UiText.vue';
import type { TextAttrsProps } from '../UiText/UiText.vue';
import type { DefineAttrsProps } from '../../../types';

export type RadioModelValue = number | string | Record<string, unknown>;
export interface RadioProps {
  /**
   * Use this props or v-model to set checked.
   */
  modelValue?: RadioModelValue;
  /**
   * Use this props to set value of radio.
   */
  value?: RadioModelValue;
  /**
   * Use this props to set radio id
   * Default value is generated by uid i.e. `radio-<uid>`.
   */
  id?: string;
  /**
   * Use this props to disabled input.
   * Remember to use `ui-radio--is-disabled` class to style disabled radio.
   */
  disabled?: boolean;
  /**
   * Use this props to pass attrs for input element.
   */
  inputAttrs?: DefineAttrsProps<null, InputHTMLAttributes>;
  /**
   * Use this props to pass attrs for radio element.
   */
  radioElementAttrs?: DefineAttrsProps<null, HTMLAttributes>;
  /**
   * Use this props to pass attrs for label UiText
   */
  textLabelAttrs?: TextAttrsProps;
}
export type RadioAttrsProps = DefineAttrsProps<RadioProps, LabelHTMLAttributes>;
export interface RadioEmits {
  (e: 'update:modelValue', value: RadioModelValue): void;
}

const props = withDefaults(defineProps<RadioProps>(), {
  modelValue: '',
  value: '',
  id: '',
  disabled: false,
  inputAttrs: () => ({}),
  radioElementAttrs: () => ({}),
  textLabelAttrs: () => ({ tag: 'span' }),
});
const defaultProps = computed(() => {
  const tag: TextAttrsProps['tag'] = 'span';
  return {
    textLabelAttrs: {
      tag,
      ...props.textLabelAttrs,
    },
    inputAttrs: {
      disabled: props.disabled,
      ...elementsListeners.value.input,
      ...props.inputAttrs,
    },
  };
});
const emit = defineEmits<RadioEmits>();
const slots = useSlots();
const {
  attrs, listeners,
} = useAttributes<LabelHTMLAttributes>();
const elementsListeners = computed(() => {
  const {
    onFocus, onBlur, ...rest
  } = listeners.value;
  return {
    input: {
      onFocus,
      onBlur,
    },
    label: rest,
  };
});
const hasLabel = computed(() => (!!slots.default));
const radioId = computed(() => (
  props.id || `radio-${uid()}`
));
const isChecked = computed(() => (equal(
  JSON.parse(JSON.stringify(props.value)),
  JSON.parse(JSON.stringify(props.modelValue)),
)));
const changeHandler = (event: Event) => {
  const el = event.target as HTMLInputElement;
  if (el.checked) {
    emit('update:modelValue', JSON.parse(JSON.stringify(props.value)));
  }
};
// TODO: remove in 0.6.0 / BEGIN
const radiobutton = computed(() => (slots.radiobutton));
if (radiobutton.value) {
  if (process.env.NODE_ENV === 'development') {
    console.warn('[@infermedica/component-library error][UiRadio]: The `radiobutton` slot will be removed in 0.6.0. Please use `radio` slot instead.');
  }
}
// END
</script>

<style lang="scss">
@use "../../../styles/functions";
@use "../../../styles/mixins";

.ui-radio {
  $this: &;
  $element: radio;

  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  gap: functions.var($element, gap, var(--space-12));

  @include mixins.with-hover {
    cursor: pointer;
  }

  @include mixins.hover {
    #{$this}__radio {
      &::after {
        @include mixins.use-logical($element + "-hover", border-color, var(--color-border-strong-hover));
      }

      &--is-checked {
        &::after {
          @include mixins.use-logical(
            $element + "-checked-hover",
            border-color,
            var(--color-selectioncontrols-selection-hover)
            );
        }

        #{$this}__mark {
          background:
            functions.var(
              $element + "-checked-hover-mark",
              color,
              var(--color-selectioncontrols-selection-hover)
            );
        }
      }
    }
  }

  &:active {
    #{$this}__radio {
      &::after {
        @include mixins.use-logical($element + "-active", border-color, var(--color-border-strong-active));
      }

      &--is-checked {
        &::after {
          @include mixins.use-logical(
            $element + "-checked-active",
            border-color,
            var(--color-selectioncontrols-selection-active)
            );
        }

        #{$this}__mark {
          background:
            functions.var(
              $element + "-checked-active-mark",
              color,
              var(--color-selectioncontrols-selection-active)
            );
        }
      }
    }
  }

  @include mixins.with-focus {
    &:focus-within {
      #{$this}__radio {
        box-shadow: var(--focus-outer);
      }
    }
  }

  &__radio {
    @include mixins.inner-border(
      $element,
      $color: var(--color-border-strong),
      $width: 2px,
      $radius: var(--border-radius-circle),
      $transition: (
        border-color 150ms ease-in-out,
        background-color 150ms ease-in-out
      )
    );
    @include mixins.use-logical($element + "-radio", margin, var(--space-2));

    position: relative;
    display: flex;
    width: functions.var($element, size, 1.25rem);
    height: functions.var($element, size, 1.25rem);
    flex: none;
    align-items: center;
    justify-content: center;
    background: functions.var($element, background, var(--color-background-white));

    &--is-checked {
      &::after {
        @include mixins.use-logical($element + "-checked", border-color, var(--color-selectioncontrols-selection));
      }

      #{$this}__mark {
        background: functions.var($element + "-checked-mark", color, var(--color-selectioncontrols-selection));
      }
    }
  }

  &__mark {
    position: absolute;
    top: 50%;
    left: 50%;
    width: functions.var($element + "-mark", size, 0.625rem);
    height: functions.var($element + "-mark", size, 0.625rem);
    background: functions.var($element + "-mark", color, transparent);
    border-radius: inherit;
    transform: translate(-50%, -50%);
  }

  &__label {
    --text-margin: #{functions.var($element + "-label", margin, 0 0 0 var(--space-12))};
    --text-color: #{functions.var($element + "-label", color, var(--color-text-body))};

    flex: 1;
  }

  &--is-disabled {
    cursor: not-allowed;

    @include mixins.hover {
      #{$this}__radio {
        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          &::after {
            @include mixins.use-logical($element + "-checked", border-color, var(--color-icon-disabled));
          }

          #{$this}__mark {
            background: functions.var($element + "-checked-mark", color, var(--color-icon-disabled));
          }
        }
      }
    }

    &:active {
      #{$this}__radio {
        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          &::after {
            @include mixins.use-logical($element + "-checked", border-color, var(--color-icon-disabled));
          }

          #{$this}__mark {
            background: functions.var($element + "-checked-mark", color, var(--color-icon-disabled));
          }
        }
      }
    }

    #{$this}__radio {
      &::after {
        @include mixins.use-logical($element + "-checked", border-color, var(--color-icon-disabled));
      }

      &--is-checked {
        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-icon-disabled));
        }

        #{$this}__mark {
          background: functions.var($element + "-checked-mark", color, var(--color-icon-disabled));
        }
      }
    }

    #{$this}__label {
      --text-color: #{functions.var($element + "-label", color, var(--color-text-disabled))};
    }
  }

  &--has-error {
    @include mixins.hover {
      #{$this}__radio {
        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-border-error-strong-hover));
        }

        &--is-checked {
          &::after {
            @include mixins.use-logical($element + "-checked", border-color, var(--color-border-error-strong-hover));
          }

          #{$this}__mark {
            background: functions.var($element + "-checked-mark", color, var(--color-border-error-strong-hover));
          }
        }
      }
    }

    &:active {
      #{$this}__radio {
        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-border-error-strong-active));
        }

        &--is-checked {
          &::after {
            @include mixins.use-logical($element + "-checked", border-color, var(--color-border-error-strong-active));
          }

          #{$this}__mark {
            background: functions.var($element + "-checked-mark", color, var(--color-border-error-strong-active));
          }
        }
      }
    }

    #{$this}__radio {
      &::after {
        @include mixins.use-logical($element + "-checked", border-color, var(--color-border-error-strong));
      }

      &--is-checked {
        &::after {
          @include mixins.use-logical($element + "-checked", border-color, var(--color-border-error-strong));
        }

        #{$this}__mark {
          background: functions.var($element + "-checked-mark", color, var(--color-border-error-strong));
        }
      }
    }
  }
}
</style>
