<template>
  <label
    class="ui-radio"
    :for="radioId"
    v-bind="getRootAttrs($attrs)"
  >
    <input
      :id="radioId"
      v-keyboard-focus
      type="radio"
      class="visual-hidden"
      :checked="isChecked"
      v-bind="getInputAttrs($attrs)"
      @change="changeHandler($event)"
    >
    <!-- @slot Use this slot to replace radiobutton template. -->
    <slot
      name="radio"
      v-bind="{checked: isChecked}"
    >
      <div
        class="ui-radio__radio"
        :class="{'ui-radio__radio--is-checked': isChecked}"
      >
        <div
          class="ui-radio__mark"
        />
      </div>
    </slot>
    <!-- @slot Use this slot to replace label template. -->
    <slot name="label">
      <UiText
        v-if="hasLabel"
        tag="span"
        class="ui-radio__label"
      >
        <!-- @slot Use this slot to place content inside label. -->
        <slot />
      </UiText>
    </slot>
  </label>
</template>

<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>

<script setup lang="ts">
import { computed, useSlots } from 'vue';
import type { PropType } from 'vue';
import equal from 'fast-deep-equal';
import { uid } from 'uid/single';
import UiText from '../UiText/UiText.vue';
import useInput from '../../../composable/useInput';
import { keyboardFocus as vKeyboardFocus } from '../../../utilities/directives';

export type RadioValue = number | string | Record<string, unknown>;
const props = defineProps({
  /**
   * Use this props to set radio id
   * Default value is generated by uid i.e. `radio-<uid>`.
   */
  id: {
    type: String,
    default: '',
  },
  /**
   * Use this props to set value of radio.
   */
  value: {
    type: [Number, String, Object] as PropType<RadioValue>,
    default: '',
  },
  /**
   * Use this props or v-model to set checked.
   */
  modelValue: {
    type: [Number, String, Object] as PropType<RadioValue>,
    default: '',
  },
});
const emit = defineEmits<{(e: 'update:modelValue', value: RadioValue): void
}>();
const slots = useSlots();
const hasLabel = computed(() => (!!slots.default));
const radioId = computed(() => (
  props.id || `radio-${uid()}`
));
const isChecked = computed(() => (equal(
  JSON.parse(JSON.stringify(props.value)),
  JSON.parse(JSON.stringify(props.modelValue)),
)));
const { getRootAttrs, getInputAttrs } = useInput();
function changeHandler(event: Event) {
  const el = event.target as HTMLInputElement;
  if (el.checked) {
    emit('update:modelValue', JSON.parse(JSON.stringify(props.value)));
  }
}

// TODO: remove in 0.6.0
const { radiobutton } = slots;
if (radiobutton) {
  throw new Error('[@infermedica/component-library error][UiRadio]: The `radiobutton` slot is deprecated and removed. Please use `radio` slot instead.');
}
// END
</script>

<style lang="scss">
@import "../../../styles/mixins/mixins";
@import "../../../styles/functions/functions";

.ui-radio {
  $this: &;
  $element: radio;

  display: flex;
  align-items: flex-start;
  justify-content: flex-start;

  @include with-hover {
    cursor: pointer;
  }

  @include hover {
    #{$this}__radio {
      &::after {
        border-color: css-var($element + "-hover", border-color, var(--color-border-strong-hover));
      }

      &--is-checked {
        &::after {
          border-color:
            css-var(
              $element + "-checked-hover",
              border-color,
              var(--color-selectioncontrols-selection-hover)
            );
        }

        #{$this}__mark {
          background: css-var($element + "-checked-hover-mark", color, var(--color-selectioncontrols-selection-hover));
        }
      }
    }
  }

  &:active {
    #{$this}__radio {
      &::after {
        border-color: css-var($element + "-active", border-color, var(--color-border-strong-active));
      }

      &--is-checked {
        &::after {
          border-color:
            css-var(
              $element + "-checked-active",
              border-color,
              var(--color-selectioncontrols-selection-active)
            );
        }

        #{$this}__mark {
          background:
            css-var(
              $element + "-checked-active-mark",
              color,
              var(--color-selectioncontrols-selection-active)
            );
        }
      }
    }
  }

  @include with-focus {
    &:focus-within {
      #{$this}__radio {
        box-shadow: var(--focus-outer);
      }
    }
  }

  &__radio {
    @include inner-border(
      $element,
      $color: var(--color-border-strong),
      $width: 2px,
      $radius: var(--border-radius-circle),
      $transition: (
        border-color 150ms ease-in-out,
        background-color 150ms ease-in-out
      )
    );

    position: relative;
    display: flex;
    width: css-var($element, size, 1.25rem);
    height: css-var($element, size, 1.25rem);
    flex: none;
    align-items: center;
    justify-content: center;
    margin: 2px;
    background: css-var($element, background, var(--color-background-white));

    &--is-checked {
      &::after {
        border-color: css-var($element + "-checked", border-color, var(--color-selectioncontrols-selection));
      }

      #{$this}__mark {
        background: css-var($element + "-checked-mark", color, var(--color-selectioncontrols-selection));
      }
    }
  }

  &__mark {
    position: absolute;
    top: 50%;
    left: 50%;
    width: css-var($element + "-mark", size, 0.625rem);
    height: css-var($element + "-mark", size, 0.625rem);
    background: css-var($element + "-mark", color, transparent);
    border-radius: inherit;
    transform: translate(-50%, -50%);
  }

  &__label {
    --text-color: #{css-var($element + "-label", color, var(--color-text-body))};

    flex: 1;
    margin: css-var($element + "-label", margin, 0 0 0 var(--space-12));

    [dir="rtl"] & {
      margin: css-var($element + "-rtl-label", margin, 0 var(--space-12) 0 0);
    }
  }

  &--is-disabled {
    cursor: not-allowed;

    @include hover {
      #{$this}__radio {
        &::after {
          border-color: css-var($element + "-checked", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          &::after {
            border-color: css-var($element + "-checked", border-color, var(--color-icon-disabled));
          }

          #{$this}__mark {
            background: css-var($element + "-checked-mark", color, var(--color-icon-disabled));
          }
        }
      }
    }

    &:active {
      #{$this}__radio {
        &::after {
          border-color: css-var($element + "-checked", border-color, var(--color-icon-disabled));
        }

        &--is-checked {
          &::after {
            border-color: css-var($element + "-checked", border-color, var(--color-icon-disabled));
          }

          #{$this}__mark {
            background: css-var($element + "-checked-mark", color, var(--color-icon-disabled));
          }
        }
      }
    }

    #{$this}__radio {
      &::after {
        border-color: css-var($element + "-checked", border-color, var(--color-icon-disabled));
      }

      &--is-checked {
        &::after {
          border-color: css-var($element + "-checked", border-color, var(--color-icon-disabled));
        }

        #{$this}__mark {
          background: css-var($element + "-checked-mark", color, var(--color-icon-disabled));
        }
      }
    }

    #{$this}__label {
      --text-color: #{css-var($element + "-label", color, var(--color-text-disabled))};
    }
  }

  &--has-error {
    @include hover {
      #{$this}__radio {
        &::after {
          border-color: css-var($element + "-checked", border-color, var(--color-border-error-strong-hover));
        }

        &--is-checked {
          &::after {
            border-color: css-var($element + "-checked", border-color, var(--color-border-error-strong-hover));
          }

          #{$this}__mark {
            background: css-var($element + "-checked-mark", color, var(--color-border-error-strong-hover));
          }
        }
      }
    }

    &:active {
      #{$this}__radio {
        &::after {
          border-color: css-var($element + "-checked", border-color, var(--color-border-error-strong-active));
        }

        &--is-checked {
          &::after {
            border-color: css-var($element + "-checked", border-color, var(--color-border-error-strong-active));
          }

          #{$this}__mark {
            background: css-var($element + "-checked-mark", color, var(--color-border-error-strong-active));
          }
        }
      }
    }

    #{$this}__radio {
      &::after {
        border-color: css-var($element + "-checked", border-color, var(--color-border-error-strong));
      }

      &--is-checked {
        &::after {
          border-color: css-var($element + "-checked", border-color, var(--color-border-error-strong));
        }

        #{$this}__mark {
          background: css-var($element + "-checked-mark", color, var(--color-border-error-strong));
        }
      }
    }
  }
}
</style>
