<template>
  <div class="ui-phone-number">
    <!-- @slot Use this slot to replace label template.-->
    <slot
      name="label"
      v-bind="{
        message,
        id: inputId,
        textMessageAttrs: defaultProps.textMessageAttrs,
      }"
    >
      <label
        v-if="message"
        :for="inputId"
      >
        <!-- @slot Use this slot to replace message template.-->
        <slot
          name="message"
          v-bind="{
            message,
            textMessageAttrs: defaultProps.textMessageAttrs,
          }"
        >
          <UiText
            v-bind="defaultProps.textMessageAttrs"
            class="ui-text--body-2-comfortable"
          >
            {{ message }}
          </UiText>
        </slot>
      </label>
    </slot>
    <!-- @slot Use this slot to replace phone number fields template.-->
    <slot
      name="phone-number-fields"
      v-bind="{
        prefix,
        inputId,
        phoneNumber,
        placeholder,
      }"
    >
      <div
        class="ui-phone-number-form-fields"
      >
        <!-- @slot Use this slot to replace phone number prefix template.-->
        <slot
          name="phone-number-prefix"
          v-bind="{
            prefix,
            languageData,
          }"
        >
          <UiPhoneNumberPrefix
            v-model="prefix"
            :language-data="languageData"
          />
        </slot>
        <!-- @slot Use this slot to replace phone number template.-->
        <slot
          name="phone-number-input"
          v-bind="{
            inputId,
            phoneNumber,
            placeholder,
          }"
        >
          <UiPhoneNumberInput
            :id="inputId"
            v-model="phoneNumber"
            :error-message="errorMessage"
            :placeholder="placeholder"
          />
        </slot>
      </div>
    </slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { uid } from 'uid/single';
import UiText from '../../atoms/UiText/UiText.vue';
import UiPhoneNumberPrefix from './_internal/UiPhoneNumberPrefix/UiPhoneNumberPrefix.vue';
import UiPhoneNumberInput from './_internal/UiPhoneNumberInput/UiPhoneNumberInput.vue';
import type {
  PhoneCodeType,
  SupportedCountryCodeType,
} from '../../../utilities/helpers';
import type { TextAttrsProps } from '../../atoms/UiText/UiText.vue';

export interface UiPhoneNumberProps {
  /**
   * Use this props to set message text.
   */
  message?: string,
  /**
   * Use this props to set input id and label for
   * Default value is generated by uid i.e. `input-<uid>`.
   */
   id?: string,
  /**
   * Use this props to set default prefix phone code.
   */
  prefix?: PhoneCodeType,
  /**
   * Use this props to pass phone number.
   */
  phoneNumber?: string,
  /**
   * Use this props to set input placeholder.
   */
  placeholder?: string,
  /**
   * Use this props to set alert message.
   */
  errorMessage?: boolean | string,
  /**
   * Use this props to pass attrs to message UiText.
   */
   textMessageAttrs?: TextAttrsProps;
   /**
   * Use this props to set phone number prefix default language.
   */
   languageData?: {
    country: SupportedCountryCodeType,
    language: string,
   },
}

const emit = defineEmits([
  'update:prefix',
  'update:phoneNumber',
]);

const props = withDefaults(defineProps<UiPhoneNumberProps>(), {
  message: 'Phone number',
  id: '',
  prefix: () => ({
    code: '+1',
    countryCode: 'US',
    country: 'United States of America',
  }),
  phoneNumber: '',
  placeholder: 'Enter phone number',
  errorMessage: false,
  textMessageAttrs: () => ({ tag: 'span' }),
  languageData: () => ({
    country: 'us',
    language: 'en',
  }),
});

const defaultProps = computed(() => {
  const tag: TextAttrsProps['tag'] = 'span';
  return {
    textMessageAttrs: {
      tag,
      ...props.textMessageAttrs,
    },
  };
});

const inputId = computed(() => (
  props.id || `input-${uid()}`
));

const prefix = computed({
  get: () => props.prefix,
  set: (value) => emit('update:prefix', value),
});

const phoneNumber = computed({
  get: () => props.phoneNumber,
  set: (value) => emit('update:phoneNumber', value),
});

</script>

<style lang="scss">
@use "../../../styles/functions";

.ui-phone-number {
  --phone-number-dropdown-width: 320px;

  width: var(--phone-number-dropdown-width);

  &-form-fields {
    display: flex;
    flex-direction: column;
    gap: var(--space-8);
    margin-top: var(--space-8);
  }
}
</style>
