name: TMP Release
on:
  pull_request:
    branches:
      - 'releases/**'
    types:
      - opened
jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
